/**
 * Connector Framework
 *
 * Standard interface for external system integrations.
 * Each connector transforms source-specific data into
 * CrossDomainSignal[] for the event bus pipeline.
 */

import type { SupabaseClient } from '@supabase/supabase-js';

// ============================================================================
// TYPES
// ============================================================================

/**
 * Signal format used by connectors for database storage.
 * This is a superset of CrossDomainSignal that includes
 * organization_id and metadata for persistence.
 */
export interface ConnectorSignal {
  organization_id: string;
  source_domain: string;
  signal_type: string;
  signal_value: number;
  entity_type?: string;
  entity_id?: string;
  client_id?: string;
  metadata?: Record<string, unknown>;
}

export interface ConnectorSyncResult {
  success: boolean;
  signalsGenerated: number;
  recordsProcessed: number;
  errors: string[];
  duration_ms: number;
  lastSyncedAt: Date;
}

export interface NexusConnector {
  /** Unique connector identifier */
  id: string;
  /** Human-readable name */
  name: string;
  /** Domain this connector feeds (finance, revenue, cs, etc.) */
  domain: string;
  /** Full sync from source system */
  fullSync(
    supabase: SupabaseClient,
    organizationId: string
  ): Promise<ConnectorSyncResult>;
  /** Incremental sync since last sync */
  incrementalSync(
    supabase: SupabaseClient,
    organizationId: string,
    since: Date
  ): Promise<ConnectorSyncResult>;
  /** Handle real-time webhook from source system (optional) */
  handleWebhook?(payload: unknown): ConnectorSignal[];
}

// ============================================================================
// HELPERS
// ============================================================================

/**
 * Store signals generated by a connector into the database
 */
export async function storeConnectorSignals(
  supabase: SupabaseClient,
  signals: ConnectorSignal[]
): Promise<void> {
  if (signals.length === 0) return;

  const rows = signals.map((s) => ({
    organization_id: s.organization_id,
    source_domain: s.source_domain,
    signal_type: s.signal_type,
    signal_value: s.signal_value,
    entity_type: s.entity_type || null,
    entity_id: s.entity_id || null,
    client_id: s.client_id || null,
    metadata: s.metadata || {},
    created_at: new Date().toISOString(),
  }));

  await supabase.from('cross_domain_signals').insert(rows);
}

/**
 * Record sync result in tracking table
 */
export async function recordSyncResult(
  supabase: SupabaseClient,
  connectorId: string,
  organizationId: string,
  result: ConnectorSyncResult
): Promise<void> {
  await supabase.from('connector_sync_log').insert({
    connector_id: connectorId,
    organization_id: organizationId,
    success: result.success,
    signals_generated: result.signalsGenerated,
    records_processed: result.recordsProcessed,
    errors: result.errors,
    duration_ms: result.duration_ms,
    synced_at: result.lastSyncedAt.toISOString(),
  });
}
