/**
 * Connector Framework
 *
 * Standard interface for external system integrations.
 * Each connector transforms source-specific data into
 * CrossDomainSignal[] for the event bus pipeline.
 */

import type { SupabaseClient } from '@supabase/supabase-js';

// ============================================================================
// TYPES
// ============================================================================

/**
 * Signal format used by connectors for database storage.
 * This is a superset of CrossDomainSignal that includes
 * organization_id and metadata for persistence.
 */
export interface ConnectorSignal {
  organization_id: string;
  source_domain: string;
  signal_type: string;
  signal_value: number;
  entity_type?: string;
  entity_id?: string;
  client_id?: string;
  metadata?: Record<string, unknown>;
}

export interface ConnectorSyncResult {
  success: boolean;
  signalsGenerated: number;
  recordsProcessed: number;
  errors: string[];
  duration_ms: number;
  lastSyncedAt: Date;
}

export interface NexusConnector {
  /** Unique connector identifier */
  id: string;
  /** Human-readable name */
  name: string;
  /** Domain this connector feeds (finance, revenue, cs, etc.) */
  domain: string;
  /** Full sync from source system */
  fullSync(
    supabase: SupabaseClient,
    organizationId: string
  ): Promise<ConnectorSyncResult>;
  /** Incremental sync since last sync */
  incrementalSync(
    supabase: SupabaseClient,
    organizationId: string,
    since: Date
  ): Promise<ConnectorSyncResult>;
  /** Handle real-time webhook from source system (optional) */
  handleWebhook?(payload: unknown): ConnectorSignal[];
}

// ============================================================================
// ENTITY RESOLUTION INTEGRATION
// ============================================================================

/**
 * Entity resolver hook for connectors.
 * When provided to storeConnectorSignals, signals are resolved through
 * the entity resolver to link cross-domain entities.
 */
export interface ConnectorEntityResolver {
  resolve(input: {
    source: string;
    externalId: string;
    displayName?: string;
    entityType?: string;
    email?: string;
    domain?: string;
  }): Promise<{ canonicalId: string; confidence: number } | null>;
}

// ============================================================================
// HELPERS
// ============================================================================

/**
 * Store signals generated by a connector into the database.
 *
 * SECURITY: When scopedOrganizationId is provided, all signals are forced
 * to use that organization_id regardless of what's in the payload. This
 * prevents signal injection attacks where a malicious payload spoofs a
 * different org's organization_id.
 *
 * When an entityResolver is provided, signals with entity_id are resolved
 * through the L2 entity resolution layer to link cross-domain entities.
 * The original entity_id is preserved in metadata.original_entity_id.
 */
export async function storeConnectorSignals(
  supabase: SupabaseClient,
  signals: ConnectorSignal[],
  entityResolver?: ConnectorEntityResolver,
  scopedOrganizationId?: string
): Promise<void> {
  if (signals.length === 0) return;

  // SECURITY: Enforce organization_id scoping to prevent cross-tenant injection.
  // When scopedOrganizationId is provided, override all signal org IDs.
  // When not provided, validate that all signals have an organization_id.
  if (scopedOrganizationId) {
    signals = signals.map((s) => ({
      ...s,
      organization_id: scopedOrganizationId,
    }));
  } else {
    // Validate every signal has an organization_id
    const missingOrgId = signals.filter((s) => !s.organization_id);
    if (missingOrgId.length > 0) {
      throw new Error(
        `Signal injection blocked: ${missingOrgId.length} signal(s) missing organization_id. ` +
        `Provide scopedOrganizationId parameter or ensure all signals have organization_id.`
      );
    }
  }

  // Resolve entities through L2 if resolver is provided
  let resolvedSignals = signals;
  if (entityResolver) {
    resolvedSignals = await Promise.all(
      signals.map(async (signal) => {
        if (!signal.entity_id || !signal.entity_type) return signal;

        try {
          const resolved = await entityResolver.resolve({
            source: signal.source_domain,
            externalId: signal.entity_id,
            displayName: signal.metadata?.display_name as string | undefined,
            entityType: signal.entity_type,
            email: signal.metadata?.email as string | undefined,
            domain: signal.metadata?.domain as string | undefined,
          });

          if (resolved) {
            return {
              ...signal,
              entity_id: resolved.canonicalId,
              metadata: {
                ...signal.metadata,
                original_entity_id: signal.entity_id,
                resolution_confidence: resolved.confidence,
              },
            };
          }
        } catch {
          // Entity resolution failure is non-fatal — keep original entity_id
        }

        return signal;
      })
    );
  }

  const rows = resolvedSignals.map((s) => ({
    organization_id: s.organization_id,
    source_domain: s.source_domain,
    signal_type: s.signal_type,
    signal_value: s.signal_value,
    entity_type: s.entity_type || null,
    entity_id: s.entity_id || null,
    client_id: s.client_id || null,
    metadata: s.metadata || {},
    created_at: new Date().toISOString(),
  }));

  const { error } = await supabase.from('cross_domain_signals').insert(rows);
  if (error) {
    throw new Error(`Failed to store connector signals: ${error.message}`);
  }
}

/**
 * Record sync result in tracking table
 */
export async function recordSyncResult(
  supabase: SupabaseClient,
  connectorId: string,
  organizationId: string,
  result: ConnectorSyncResult
): Promise<void> {
  const { error } = await supabase.from('connector_sync_log').insert({
    connector_id: connectorId,
    organization_id: organizationId,
    success: result.success,
    signals_generated: result.signalsGenerated,
    records_processed: result.recordsProcessed,
    errors: result.errors,
    duration_ms: result.duration_ms,
    synced_at: result.lastSyncedAt.toISOString(),
  });
  if (error) {
    throw new Error(`Failed to record sync result: ${error.message}`);
  }
}
