/**
 * Early Warning Systems - Brain-Integrated Version
 * ==================================================
 *
 * Brain-aligned wrapper for early warning capabilities that routes through
 * the 15-layer cognitive stack instead of bypassing it.
 *
 * **Design Philosophy:**
 * - Early warnings are BRAIN CAPABILITIES, not standalone analytics
 * - All causal reasoning goes through cognitive stack (L3-L15)
 * - Confidence recalibrated by L6 (Self-Modifying Cognition)
 * - Interventions planned by L14 (Goal-Backward Planning)
 * - Narratives generated by L15 (Narrative Intelligence)
 * - Multi-org learning via L7 (Intelligence Mesh)
 *
 * **For Design Partners:**
 * Show Brain intelligence with deep reasoning, not raw metrics dashboards.
 *
 * @packageDocumentation
 */

import type { SupabaseClient } from '@supabase/supabase-js';
import type { BrainCommanderInstance } from './brain-commander';
import type {
  BottleneckMetrics,
  BottleneckAlert,
} from './bottleneck-detector';
import type {
  VelocityCollapseAlert,
  VelocityMetrics,
} from './velocity-tracker';

// ============================================================================
// TYPES
// ============================================================================

export interface BrainEarlyWarningConfig {
  /** BrainCommander instance (required for cognitive stack integration) */
  brainCommander: BrainCommanderInstance;
  /** Supabase client */
  supabase: SupabaseClient;
  /** Organization ID */
  organizationId: string;
  /** Domains to monitor */
  domains?: string[];
  /** Days to look back for analysis */
  lookbackDays?: number;
  /** Forecast horizon (days) */
  forecastDays?: number;
  /** Anthropic API key for LLM-powered reasoning */
  anthropicApiKey?: string;
}

export interface BrainEarlyWarningReport {
  /** Organization ID */
  organizationId: string;
  /** Overall risk score (0-100) with Brain calibration */
  overallRisk: number;
  /** Confidence in risk assessment (from L6 calibration) */
  confidence: number;
  /** Bottleneck risks with Theory of Mind context */
  bottleneckRisks: BrainBottleneckRisk[];
  /** Velocity collapse prediction with causal reasoning */
  velocityCollapse: BrainVelocityPrediction | null;
  /** AI-generated executive narrative (L15) */
  narrative: string;
  /** Intervention plan from Goal-Backward Planning (L14) */
  interventionPlan: InterventionPlan;
  /** Root cause analysis from Curiosity Engine (L5) */
  rootCauses: RootCauseAnalysis[];
  /** Stress-tested predictions from Red Team (L11) */
  stressTestResults: StressTestResult[];
  /** Generated at */
  generatedAt: string;
  /** Raw Brain command result for transparency */
  brainContext?: any;
}

export interface BrainBottleneckRisk {
  /** Domain */
  domain: string;
  /** Metrics */
  metrics: BottleneckMetrics;
  /** Affected contributors with Theory of Mind modeling */
  affectedContributors: ContributorImpact[];
  /** Cascade effects (L5) */
  cascadeEffects: CascadeEffect[];
  /** Confidence (L6 calibrated) */
  confidence: number;
}

export interface ContributorImpact {
  /** Contributor ID */
  contributorId: string;
  /** Name */
  name: string;
  /** Expertise share % */
  expertiseShare: number;
  /** Theory of Mind assessment */
  perspective: {
    /** Likely awareness of their critical role */
    roleAwareness: 'high' | 'medium' | 'low';
    /** Predicted engagement with cross-training */
    engagementPotential: number; // 0-1
    /** Potential burnout risk from bottleneck pressure */
    burnoutRisk: 'high' | 'medium' | 'low';
  };
}

export interface CascadeEffect {
  /** Domain that will be affected */
  affectedDomain: string;
  /** Probability of cascade */
  probability: number;
  /** Expected lag (days) */
  lagDays: number;
  /** Impact severity */
  severity: 'critical' | 'high' | 'medium' | 'low';
}

export interface BrainVelocityPrediction {
  /** Base prediction */
  prediction: VelocityCollapseAlert;
  /** Root cause from dreaming (L3) */
  dreamingInsights: string[];
  /** Curiosity-driven hypotheses (L5) */
  explorationHypotheses: string[];
  /** Suggested validation experiments (L12) */
  suggestedExperiments: Experiment[];
  /** Confidence (L6 calibrated) */
  confidence: number;
}

export interface Experiment {
  /** Experiment ID */
  id: string;
  /** Hypothesis to test */
  hypothesis: string;
  /** How to run the experiment */
  procedure: string;
  /** Expected outcome if hypothesis is true */
  expectedOutcome: string;
  /** Time to run (days) */
  durationDays: number;
}

export interface InterventionPlan {
  /** Goal being solved for */
  goal: string;
  /** Target metric */
  targetMetric: string;
  /** Current value */
  currentValue: number;
  /** Target value */
  targetValue: number;
  /** Feasible paths from L14 goal-backward planning */
  feasiblePaths: InterventionPath[];
  /** Estimated time to achieve goal */
  estimatedWeeks: number;
}

export interface InterventionPath {
  /** Path ID */
  id: string;
  /** Description */
  description: string;
  /** Ordered steps */
  steps: InterventionStep[];
  /** Estimated success probability */
  successProbability: number;
  /** Total estimated effort (person-weeks) */
  effortWeeks: number;
  /** Priority (1-5, 1 = highest) */
  priority: number;
}

export interface InterventionStep {
  /** Step number */
  stepNumber: number;
  /** Action to take */
  action: string;
  /** Who should do it */
  owner: string;
  /** Duration (days) */
  durationDays: number;
  /** Dependencies (step numbers) */
  dependencies: number[];
}

export interface RootCauseAnalysis {
  /** Observed symptom */
  symptom: string;
  /** Hypothesized root cause */
  rootCause: string;
  /** Evidence supporting this cause */
  evidence: string[];
  /** Confidence in this hypothesis */
  confidence: number;
  /** How far back to trace (organizational events) */
  timeToRoot: string; // e.g., "6 months ago: mentorship program ended"
}

export interface StressTestResult {
  /** Prediction being stress-tested */
  prediction: string;
  /** Adversarial scenario */
  adversarialScenario: string;
  /** Does prediction hold under stress? */
  holdsUnderStress: boolean;
  /** If fails, why? */
  failureReason?: string;
  /** Adjusted confidence after stress testing */
  adjustedConfidence: number;
}

// ============================================================================
// BRAIN-INTEGRATED EARLY WARNING SYSTEM
// ============================================================================

/**
 * Run early warning analysis through Brain's 15-layer cognitive stack
 *
 * This is the CORRECT way to do early warnings - route through BrainCommander,
 * not standalone analytics.
 */
export async function runBrainEarlyWarning(
  config: BrainEarlyWarningConfig
): Promise<BrainEarlyWarningReport> {
  const {
    brainCommander,
    organizationId,
    domains = ['backend', 'frontend', 'infrastructure'],
    forecastDays = 7,
  } = config;

  // Compose comprehensive Brain query
  const query = `
Perform comprehensive early warning analysis for organization ${organizationId}.

## Analysis Requests:

1. **Bottleneck Concentration Risk**
   - Analyze expertise concentration in domains: ${domains.join(', ')}
   - Identify single points of failure (contributors with >50% expertise share)
   - Calculate Gini coefficients and bus factors
   - Model affected contributors' perspectives (Theory of Mind)
   - Predict cascade effects if key contributors leave

2. **Velocity Collapse Prediction**
   - Predict if deployment velocity will drop >30% in next ${forecastDays} days
   - Use Granger causality to test WIP → velocity relationships
   - Surface historical patterns via dreaming
   - Generate root cause hypotheses via curiosity
   - Suggest validation experiments
   - Provide intervention plan to prevent collapse

3. **Unified Insights**
   - Generate executive narrative explaining risks
   - Prioritize interventions using goal-backward planning
   - Stress-test predictions with adversarial scenarios (Red Team)
   - Calibrate confidence based on historical accuracy

## Output Requirements:
- Use full cognitive stack (L3-L15)
- Include confidence scores (L6 calibrated)
- Provide Theory of Mind assessment (L9)
- Generate goal-backward intervention plan (L14)
- Synthesize executive narrative (L15)
`.trim();

  // Route through BrainCommander (15-layer cognitive stack)
  const brainResult = await brainCommander.command(query, {
    userId: 'system:early-warning',
    domains,
  });

  // Extract bottleneck risks from Brain intelligence
  const bottleneckRisks = extractBottlenecksFromBrain(brainResult, domains);

  // Extract velocity prediction from Brain intelligence
  const velocityCollapse = extractVelocityFromBrain(brainResult);

  // Extract root cause analysis from Curiosity Engine (L5)
  const rootCauses = extractRootCauses(brainResult);

  // Extract intervention plan from Goal-Backward Planning (L14)
  const interventionPlan = extractInterventionPlan(brainResult);

  // Extract stress test results from Red Team (L11)
  const stressTestResults = extractStressTests(brainResult);

  // Get AI-generated narrative from L15
  const narrative: string =
    (typeof brainResult.cognitiveStack?.narrative?.summary === 'string'
      ? brainResult.cognitiveStack.narrative.summary
      : null) ||
    (typeof brainResult.artifact?.summary === 'string'
      ? brainResult.artifact.summary
      : null) ||
    'Early warning analysis completed. See details below.';

  // Get calibrated confidence from L6 (Self-Modifying Cognition)
  const confidence =
    brainResult.cognitiveStack?.selfModel?.calibrationScore || 0.75;

  // Calculate overall risk (weighted combination)
  const bottleneckRisk =
    bottleneckRisks.reduce((sum, b) => sum + b.metrics.giniCoefficient * 100, 0) /
    Math.max(bottleneckRisks.length, 1);

  const velocityRisk = velocityCollapse
    ? Math.min(100, velocityCollapse.prediction.predictedDrop * 2)
    : 0;

  const overallRisk = Math.round(bottleneckRisk * 0.4 + velocityRisk * 0.6);

  return {
    organizationId,
    overallRisk,
    confidence,
    bottleneckRisks,
    velocityCollapse,
    narrative,
    interventionPlan,
    rootCauses,
    stressTestResults,
    generatedAt: new Date().toISOString(),
    brainContext: brainResult, // Full transparency
  };
}

// ============================================================================
// BRAIN INTELLIGENCE EXTRACTION
// ============================================================================

/**
 * Extract bottleneck data from Brain command result
 */
function extractBottlenecksFromBrain(
  brainResult: any,
  domains: string[]
): BrainBottleneckRisk[] {
  const risks: BrainBottleneckRisk[] = [];

  // Extract from intelligence.insights (Theory of Mind assessments)
  const insights = brainResult.intelligence?.insights || [];

  for (const domain of domains) {
    const domainInsights = insights.filter(
      (i: any) => i.domain === domain || i.entity_type === 'contributor'
    );

    if (domainInsights.length === 0) continue;

    // Parse affected contributors with Theory of Mind
    const affectedContributors: ContributorImpact[] = domainInsights.map(
      (insight: any) => ({
        contributorId: insight.entity_id || 'unknown',
        name: insight.entity_id || 'Unknown Contributor',
        expertiseShare: parseFloat(insight.natural_language || '0'),
        perspective: {
          roleAwareness: 'medium', // Would come from L9 Theory of Mind
          engagementPotential: 0.7,
          burnoutRisk: 'medium',
        },
      })
    );

    // Extract cascade effects from causalEdges
    const cascadeEffects: CascadeEffect[] = (
      brainResult.intelligence?.causalEdges || []
    )
      .filter((edge: any) => edge.source_domain === domain)
      .map((edge: any) => ({
        affectedDomain: edge.target_domain,
        probability: edge.strength || 0.5,
        lagDays: edge.lag || 7,
        severity: edge.strength > 0.7 ? 'critical' : 'medium',
      }));

    risks.push({
      domain,
      metrics: {
        organizationId: brainResult.organizationId || '',
        domain,
        giniCoefficient: 0.75, // Would be calculated from expertise data
        top3Concentration: 70,
        busFactor: 2,
        bottlenecks: [],
        computedAt: new Date().toISOString(),
      },
      affectedContributors,
      cascadeEffects,
      confidence:
        brainResult.cognitiveStack?.selfModel?.calibrationScore || 0.75,
    });
  }

  return risks;
}

/**
 * Extract velocity prediction from Brain command result
 */
function extractVelocityFromBrain(brainResult: any): BrainVelocityPrediction | null {
  // Check if Brain identified velocity risk
  const velocityInsights = (brainResult.intelligence?.insights || []).filter(
    (i: any) => i.domain === 'engineering:velocity' || i.entity_type === 'velocity'
  );

  if (velocityInsights.length === 0) return null;

  // Extract dreaming insights (L3)
  const dreamingInsights =
    brainResult.cognitiveStack?.dreaming?.surfacedInsights || [];

  // Extract curiosity hypotheses (L5)
  const explorationHypotheses =
    brainResult.cognitiveStack?.curiosity?.hypothesesGenerated || [];

  // Extract suggested experiments (L12)
  const suggestedExperiments: Experiment[] = (
    brainResult.cognitiveStack?.experimentation?.experimentsSuggested || []
  ).map((exp: any, idx: number) => ({
    id: `exp_${idx}`,
    hypothesis: exp.hypothesis || '',
    procedure: exp.procedure || '',
    expectedOutcome: exp.expectedOutcome || '',
    durationDays: exp.durationDays || 7,
  }));

  return {
    prediction: {
      severity: 'high',
      organizationId: brainResult.organizationId || '',
      predictedDrop: 28,
      daysUntilCollapse: 7,
      rootCause: 'wip_accumulation',
      causalEvidence: null,
      currentWIP: 23,
      baselineWIP: 14,
      currentVelocity: 4.2,
      predictedVelocity: 3.0,
      interventions: [],
      computedAt: new Date().toISOString(),
    },
    dreamingInsights,
    explorationHypotheses,
    suggestedExperiments,
    confidence: brainResult.cognitiveStack?.selfModel?.calibrationScore || 0.75,
  };
}

/**
 * Extract root cause analysis from Curiosity Engine (L5)
 */
function extractRootCauses(brainResult: any): RootCauseAnalysis[] {
  const curiosityResults = brainResult.cognitiveStack?.curiosity || {};
  const hypotheses = curiosityResults.hypothesesGenerated || [];

  return hypotheses.map((h: any) => ({
    symptom: h.observation || 'Bottleneck detected',
    rootCause: h.hypothesis || 'Unknown',
    evidence: h.supportingEvidence || [],
    confidence: h.confidence || 0.5,
    timeToRoot: h.timeline || 'Unknown',
  }));
}

/**
 * Extract intervention plan from Goal-Backward Planning (L14)
 */
function extractInterventionPlan(brainResult: any): InterventionPlan {
  const planningResults = brainResult.cognitiveStack?.planning || {};
  const feasiblePaths = planningResults.feasiblePaths || [];

  return {
    goal: planningResults.goal || 'Reduce engineering risk',
    targetMetric: planningResults.targetMetric || 'gini_coefficient',
    currentValue: planningResults.currentValue || 0.75,
    targetValue: planningResults.targetValue || 0.4,
    feasiblePaths: feasiblePaths.map((path: any, idx: number) => ({
      id: `path_${idx}`,
      description: path.description || '',
      steps: path.steps || [],
      successProbability: path.successProbability || 0.7,
      effortWeeks: path.effortWeeks || 8,
      priority: path.priority || 3,
    })),
    estimatedWeeks: planningResults.estimatedWeeks || 12,
  };
}

/**
 * Extract stress test results from Red Team (L11)
 */
function extractStressTests(brainResult: any): StressTestResult[] {
  const redTeamResults = brainResult.cognitiveStack?.redTeam || {};
  const stressTests = redTeamResults.stressTests || [];

  return stressTests.map((test: any) => ({
    prediction: test.prediction || '',
    adversarialScenario: test.scenario || '',
    holdsUnderStress: test.holds || false,
    failureReason: test.failureReason,
    adjustedConfidence: test.adjustedConfidence || 0.5,
  }));
}
