/**
 * Proactive Intelligence — Push-Based Insight Delivery
 * ══════════════════════════════════════════════════════════
 *
 * Claude-level capability: Instead of waiting for questions, proactively
 * surfaces insights, warnings, and opportunities based on continuous
 * monitoring of the brain's knowledge state.
 *
 * Brain Analog: The Amygdala + Reticular Activating System — the brain's
 * alerting system that elevates important signals to conscious attention
 * before being asked.
 *
 * Features:
 * - Threshold-based alerting (metric crosses a boundary)
 * - Trend-based alerts (metric is on a concerning trajectory)
 * - Cascade early warning (cascade pattern starting to form)
 * - Knowledge decay alerts (stale information)
 * - Opportunity detection (positive signals that need attention)
 * - Alert deduplication and throttling
 * - Priority-based delivery (critical > warning > info)
 * - Configurable notification channels
 *
 * @example
 * ```typescript
 * const proactive = createProactiveIntelligence({
 *   onAlert: (alert) => sendSlackMessage(alert.channel, alert.message),
 * });
 *
 * // Register monitors
 * proactive.addMonitor({
 *   name: 'churn_spike',
 *   domain: 'cs',
 *   check: (state) => state.churn_rate > 0.05,
 *   severity: 'critical',
 *   message: 'Churn rate exceeded 5% threshold',
 * });
 *
 * // Run monitoring cycle
 * const alerts = await proactive.scan(currentState);
 * console.log(alerts);  // [{severity: 'critical', ...}]
 * ```
 *
 * @packageDocumentation
 */

// ============================================================================
// TYPES
// ============================================================================

/** Configuration for proactive intelligence */
export interface ProactiveIntelligenceConfig {
  /** Callback when an alert fires */
  onAlert?: (alert: ProactiveAlert) => Promise<void> | void;
  /** Minimum time between duplicate alerts (default: 4 hours) */
  alertCooldownMs?: number;
  /** Maximum alerts per scan cycle (default: 10) */
  maxAlertsPerScan?: number;
  /** Whether to track alert history (default: true) */
  trackHistory?: boolean;
  /** Verbose logging */
  verbose?: boolean;
}

/** A monitor that watches for specific conditions */
export interface ProactiveMonitor {
  /** Unique monitor ID */
  id: string;
  /** Monitor name */
  name: string;
  /** Domain being monitored */
  domain: string;
  /** Check function — returns true if alert should fire */
  check: (state: Record<string, unknown>) => boolean;
  /** Alert severity */
  severity: 'critical' | 'warning' | 'info' | 'opportunity';
  /** Message template (can use {{key}} placeholders) */
  message: string;
  /** Whether this monitor is active */
  enabled: boolean;
  /** Custom metadata */
  metadata?: Record<string, unknown>;
}

/** A proactive alert generated by monitoring */
export interface ProactiveAlert {
  /** Unique alert ID */
  id: string;
  /** Monitor that triggered this */
  monitorId: string;
  /** Monitor name */
  monitorName: string;
  /** Severity level */
  severity: 'critical' | 'warning' | 'info' | 'opportunity';
  /** Domain */
  domain: string;
  /** Alert message */
  message: string;
  /** When the alert was generated */
  timestamp: Date;
  /** Current state snapshot that triggered the alert */
  stateSnapshot: Record<string, unknown>;
  /** Whether the alert has been acknowledged */
  acknowledged: boolean;
  /** Whether the alert has been delivered to the user */
  delivered: boolean;
  /** Recommended actions */
  recommendations: string[];
  /** Related domains that might be affected */
  relatedDomains: string[];
}

/** Result of a monitoring scan cycle */
export interface ProactiveScanResult {
  /** Alerts generated in this scan */
  alerts: ProactiveAlert[];
  /** Monitors checked */
  monitorsChecked: number;
  /** Monitors that fired */
  monitorsFired: number;
  /** Monitors throttled (on cooldown) */
  monitorsThrottled: number;
  /** Scan duration in ms */
  durationMs: number;
  /** State health summary */
  healthSummary: {
    criticalAlerts: number;
    warningAlerts: number;
    infoAlerts: number;
    opportunities: number;
  };
  /** Natural language briefing */
  briefing: string;
}

/** Built-in monitor templates */
export interface MonitorTemplate {
  /** Template name */
  name: string;
  /** Domain */
  domain: string;
  /** Severity */
  severity: ProactiveMonitor['severity'];
  /** Description */
  description: string;
  /** Factory to create the monitor */
  create: (params: Record<string, unknown>) => ProactiveMonitor;
}

// ============================================================================
// BUILT-IN MONITOR TEMPLATES
// ============================================================================

const BUILT_IN_TEMPLATES: MonitorTemplate[] = [
  {
    name: 'threshold_breach',
    domain: 'any',
    severity: 'critical',
    description: 'Alert when a metric crosses a threshold',
    create: (params) => ({
      id: `threshold_${params.metric}_${Date.now()}`,
      name: `${params.metric} threshold breach`,
      domain: (params.domain as string) || 'unknown',
      check: (state) => {
        const value = getNestedValue(state, params.metric as string);
        if (typeof value !== 'number') return false;
        const threshold = params.threshold as number;
        const direction = params.direction as string || 'above';
        return direction === 'above' ? value > threshold : value < threshold;
      },
      severity: (params.severity as ProactiveMonitor['severity']) || 'critical',
      message: `${params.metric} has breached the ${params.direction || 'above'} threshold of ${params.threshold}`,
      enabled: true,
      metadata: params,
    }),
  },
  {
    name: 'stale_data',
    domain: 'any',
    severity: 'warning',
    description: 'Alert when data is too old',
    create: (params) => ({
      id: `stale_${params.source}_${Date.now()}`,
      name: `${params.source} data staleness`,
      domain: (params.domain as string) || 'unknown',
      check: (state) => {
        const lastUpdated = getNestedValue(state, `${params.source}_last_updated`);
        if (!lastUpdated) return true; // No data = stale
        const age = Date.now() - new Date(lastUpdated as string).getTime();
        const maxAgeMs = ((params.maxAgeHours as number) || 24) * 60 * 60 * 1000;
        return age > maxAgeMs;
      },
      severity: 'warning',
      message: `Data from ${params.source} is stale (older than ${params.maxAgeHours || 24} hours)`,
      enabled: true,
      metadata: params,
    }),
  },
  {
    name: 'cascade_forming',
    domain: 'any',
    severity: 'warning',
    description: 'Alert when multiple related domains show simultaneous changes',
    create: (params) => ({
      id: `cascade_${Date.now()}`,
      name: 'Cross-domain cascade forming',
      domain: 'cross-domain',
      check: (state) => {
        const domains = (params.watchDomains as string[]) || [];
        let changedCount = 0;
        for (const domain of domains) {
          const changed = getNestedValue(state, `${domain}_changed`);
          if (changed) changedCount++;
        }
        return changedCount >= ((params.minDomains as number) || 2);
      },
      severity: 'warning',
      message: 'Multiple domains showing simultaneous changes — potential cascade forming',
      enabled: true,
      metadata: params,
    }),
  },
];

// ============================================================================
// HELPERS
// ============================================================================

function getNestedValue(obj: Record<string, unknown>, path: string): unknown {
  const parts = path.split('.');
  let current: unknown = obj;
  for (const part of parts) {
    if (current == null || typeof current !== 'object') return undefined;
    current = (current as Record<string, unknown>)[part];
  }
  return current;
}

function generateAlertId(): string {
  return `alert_${Date.now()}_${crypto.randomUUID().replace(/-/g, '').slice(0, 6)}`;
}

// ============================================================================
// FACTORY
// ============================================================================

/**
 * Create a proactive intelligence engine for push-based insight delivery.
 *
 * Monitors the brain's knowledge state and proactively surfaces alerts,
 * warnings, and opportunities without waiting for user questions.
 */
export function createProactiveIntelligence(config: ProactiveIntelligenceConfig = {}) {
  const {
    onAlert,
    alertCooldownMs = 4 * 60 * 60 * 1000, // 4 hours
    maxAlertsPerScan = 10,
    trackHistory = true,
    verbose = false,
  } = config;

  const monitors: Map<string, ProactiveMonitor> = new Map();
  const alertHistory: ProactiveAlert[] = [];
  const lastFired: Map<string, number> = new Map(); // monitorId → last fire timestamp

  return {
    /**
     * Add a monitor to the proactive intelligence system.
     */
    addMonitor(monitor: ProactiveMonitor): void {
      monitors.set(monitor.id, monitor);
    },

    /**
     * Remove a monitor by ID.
     */
    removeMonitor(id: string): boolean {
      return monitors.delete(id);
    },

    /**
     * Create a monitor from a built-in template.
     */
    createFromTemplate(templateName: string, params: Record<string, unknown>): ProactiveMonitor | null {
      const template = BUILT_IN_TEMPLATES.find((t) => t.name === templateName);
      if (!template) return null;
      const monitor = template.create(params);
      monitors.set(monitor.id, monitor);
      return monitor;
    },

    /**
     * Run a monitoring scan cycle against the current state.
     */
    async scan(state: Record<string, unknown>): Promise<ProactiveScanResult> {
      const startTime = Date.now();
      const alerts: ProactiveAlert[] = [];
      let monitorsChecked = 0;
      let monitorsFired = 0;
      let monitorsThrottled = 0;

      for (const monitor of monitors.values()) {
        if (!monitor.enabled) continue;
        monitorsChecked++;

        // Check cooldown
        const lastFiredAt = lastFired.get(monitor.id) || 0;
        if (Date.now() - lastFiredAt < alertCooldownMs) {
          monitorsThrottled++;
          continue;
        }

        try {
          const shouldFire = monitor.check(state);
          if (shouldFire && alerts.length < maxAlertsPerScan) {
            const alert: ProactiveAlert = {
              id: generateAlertId(),
              monitorId: monitor.id,
              monitorName: monitor.name,
              severity: monitor.severity,
              domain: monitor.domain,
              message: monitor.message,
              timestamp: new Date(),
              stateSnapshot: { ...state },
              acknowledged: false,
              delivered: false,
              recommendations: generateRecommendations(monitor, state),
              relatedDomains: findRelatedDomains(monitor.domain),
            };

            alerts.push(alert);
            monitorsFired++;
            lastFired.set(monitor.id, Date.now());

            if (trackHistory) {
              alertHistory.push(alert);
            }

            // Deliver alert
            if (onAlert) {
              try {
                await onAlert(alert);
                alert.delivered = true;
              } catch (err) {
                // Non-critical: alert delivery failure is non-fatal — err instanceof Error ? err.message : String(err) logged for debugging
              }
            }
          }
        } catch (err) {
          // Non-critical: monitor check failure is non-fatal — err instanceof Error ? err.message : String(err) logged for debugging
        }
      }

      // Build briefing
      const healthSummary = {
        criticalAlerts: alerts.filter((a) => a.severity === 'critical').length,
        warningAlerts: alerts.filter((a) => a.severity === 'warning').length,
        infoAlerts: alerts.filter((a) => a.severity === 'info').length,
        opportunities: alerts.filter((a) => a.severity === 'opportunity').length,
      };

      const briefingParts: string[] = [];
      if (healthSummary.criticalAlerts > 0) {
        briefingParts.push(`🚨 ${healthSummary.criticalAlerts} critical alert(s) require immediate attention.`);
      }
      if (healthSummary.warningAlerts > 0) {
        briefingParts.push(`⚠️ ${healthSummary.warningAlerts} warning(s) detected.`);
      }
      if (healthSummary.opportunities > 0) {
        briefingParts.push(`🎯 ${healthSummary.opportunities} opportunity/ies identified.`);
      }
      if (alerts.length === 0) {
        briefingParts.push('✅ All clear — no alerts from this scan cycle.');
      }

      for (const alert of alerts) {
        briefingParts.push(`- [${alert.severity.toUpperCase()}] ${alert.domain}: ${alert.message}`);
      }

      return {
        alerts,
        monitorsChecked,
        monitorsFired,
        monitorsThrottled,
        durationMs: Date.now() - startTime,
        healthSummary,
        briefing: briefingParts.join('\n'),
      };
    },

    /**
     * Get alert history.
     */
    getHistory(limit?: number): ProactiveAlert[] {
      const sorted = [...alertHistory].sort((a, b) => b.timestamp.getTime() - a.timestamp.getTime());
      return limit ? sorted.slice(0, limit) : sorted;
    },

    /**
     * Acknowledge an alert.
     */
    acknowledgeAlert(alertId: string): boolean {
      const alert = alertHistory.find((a) => a.id === alertId);
      if (alert) {
        alert.acknowledged = true;
        return true;
      }
      return false;
    },

    /**
     * Restore the last-fired timestamp for a monitor (for throttling continuity across restarts).
     * Call this before scan() to prevent duplicate alerts after agent restart.
     */
    setLastFired(monitorId: string, timestamp: number): void {
      lastFired.set(monitorId, timestamp);
    },

    /**
     * Get all registered monitors.
     */
    getMonitors(): ProactiveMonitor[] {
      return Array.from(monitors.values());
    },

    /**
     * Get available templates.
     */
    getTemplates(): MonitorTemplate[] {
      return BUILT_IN_TEMPLATES;
    },

    /**
     * Generate a proactive context section for the LLM.
     */
    getContextSection(): string {
      const recent = alertHistory
        .filter((a) => Date.now() - a.timestamp.getTime() < 24 * 60 * 60 * 1000) // Last 24h
        .sort((a, b) => b.timestamp.getTime() - a.timestamp.getTime());

      if (recent.length === 0) return '';

      const lines: string[] = ['## Proactive Intelligence Alerts (Last 24h)'];
      const criticals = recent.filter((a) => a.severity === 'critical');
      const warnings = recent.filter((a) => a.severity === 'warning');
      const opps = recent.filter((a) => a.severity === 'opportunity');

      if (criticals.length > 0) {
        lines.push('', '### 🚨 Critical');
        for (const a of criticals.slice(0, 3)) {
          lines.push(`- **${a.domain}**: ${a.message}`);
          if (a.recommendations.length > 0) {
            lines.push(`  - Recommended: ${a.recommendations[0]}`);
          }
        }
      }

      if (warnings.length > 0) {
        lines.push('', '### ⚠️ Warnings');
        for (const a of warnings.slice(0, 3)) {
          lines.push(`- **${a.domain}**: ${a.message}`);
        }
      }

      if (opps.length > 0) {
        lines.push('', '### 🎯 Opportunities');
        for (const a of opps.slice(0, 3)) {
          lines.push(`- **${a.domain}**: ${a.message}`);
        }
      }

      return lines.join('\n');
    },

    /**
     * Get configuration.
     */
    getConfig(): ProactiveIntelligenceConfig {
      return { alertCooldownMs, maxAlertsPerScan, trackHistory, verbose };
    },
  };
}

// ============================================================================
// HELPERS (private)
// ============================================================================

function generateRecommendations(monitor: ProactiveMonitor, _state: Record<string, unknown>): string[] {
  const recs: string[] = [];

  switch (monitor.severity) {
    case 'critical':
      recs.push(`Investigate ${monitor.domain} immediately`);
      recs.push('Check upstream dependencies for root cause');
      recs.push('Consider notifying stakeholders');
      break;
    case 'warning':
      recs.push(`Monitor ${monitor.domain} closely over the next 24-48 hours`);
      recs.push('Review recent changes that might have caused this');
      break;
    case 'info':
      recs.push(`Keep an eye on ${monitor.domain}`);
      break;
    case 'opportunity':
      recs.push(`Capitalize on the positive trend in ${monitor.domain}`);
      recs.push('Consider doubling down on what\'s working');
      break;
  }

  return recs;
}

function findRelatedDomains(domain: string): string[] {
  const relationships: Record<string, string[]> = {
    finance: ['revenue', 'cs', 'growth'],
    revenue: ['finance', 'marketing', 'cs'],
    cs: ['revenue', 'product', 'engineering'],
    marketing: ['revenue', 'growth', 'product'],
    engineering: ['product', 'cs'],
    product: ['engineering', 'cs', 'marketing'],
    growth: ['finance', 'marketing', 'revenue'],
    people: ['engineering', 'product'],
  };

  return relationships[domain] || [];
}
