/**
 * SE-AAS Artifacts List Page
 * ===========================
 *
 * All artifacts generated by SE-AAS domains for this workspace,
 * filterable by domain type. Models the same pattern as AAS artifacts.
 */

import { createClient } from "@/lib/supabase/server";
import { getCurrentWorkspaceId } from "@/lib/workspace-helpers";
import Link from "next/link";
import { EmptyState } from "@/components/ui/EmptyState";
import { DOMAIN_LABELS } from "@/lib/se-aas/domain-catalogue";

export const metadata = { title: "SE-AAS Artifacts" };

export default async function SeAaSArtifactsPage({
  searchParams,
}: {
  searchParams: Promise<{ domainType?: string; page?: string }>;
}) {
  const supabase = await createClient();
  const workspaceId = await getCurrentWorkspaceId();
  const { domainType, page: pageStr } = await searchParams;
  const page = Math.max(1, parseInt(pageStr ?? "1", 10) || 1);
  const limit = 20;
  const offset = (page - 1) * limit;

  // Fetch artifacts (filtered)
  let query = supabase
    .from("se_aas_artifacts")
    .select("id, domain_type, created_at, artifact_data, metadata", { count: "exact" })
    .eq("organization_id", workspaceId)
    .order("created_at", { ascending: false })
    .range(offset, offset + limit - 1);

  if (domainType) {
    query = query.eq("domain_type", domainType);
  }

  // Fetch artifacts and domain counts in parallel
  const [{ data: artifacts, count }, { data: domainCounts }] = await Promise.all([
    query,
    supabase
      .from("se_aas_artifacts")
      .select("domain_type")
      .eq("organization_id", workspaceId),
  ]);

  const countByDomain = (domainCounts ?? []).reduce<Record<string, number>>((acc, row) => {
    acc[row.domain_type] = (acc[row.domain_type] ?? 0) + 1;
    return acc;
  }, {});

  const totalPages = Math.ceil((count ?? 0) / limit);

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <div className="flex items-center gap-2 text-xs text-muted mb-1">
            <Link href="/se-aas" className="hover:text-foreground transition-colors">Engineering Intelligence</Link>
            <span>/</span>
            <span>Artifacts</span>
          </div>
          <h1 className="text-xl font-semibold tracking-tight">SE-AAS Artifacts</h1>
          <p className="text-xs text-muted mt-0.5">
            {count ?? 0} artifacts generated by this AI Worker
          </p>
        </div>
        <Link
          href="/copilot?service=seaas"
          className="px-4 py-2.5 rounded-lg bg-accent hover:bg-accent-dark text-accent-foreground text-sm font-medium transition-colors flex items-center gap-2"
        >
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M12 4v16m8-8H4" />
          </svg>
          New Artifact
        </Link>
      </div>

      {/* Domain filter pills */}
      <div className="flex flex-wrap gap-2">
        <Link
          href="/se-aas/artifacts"
          className={`px-3 py-1 rounded-full text-xs font-medium transition-colors border ${
            !domainType
              ? "bg-accent text-accent-foreground border-accent"
              : "border-border-subtle text-muted hover:text-foreground hover:border-foreground/30"
          }`}
        >
          All ({count ?? 0})
        </Link>
        {Object.entries(countByDomain)
          .sort((a, b) => b[1] - a[1])
          .map(([dt, n]) => {
            const meta = DOMAIN_LABELS[dt];
            return (
              <Link
                key={dt}
                href={`/se-aas/artifacts?domainType=${encodeURIComponent(dt)}`}
                className={`px-3 py-1 rounded-full text-xs font-medium transition-colors border flex items-center gap-1 ${
                  domainType === dt
                    ? "bg-accent text-accent-foreground border-accent"
                    : "border-border-subtle text-muted hover:text-foreground hover:border-foreground/30"
                }`}
              >
                {meta?.icon ?? "📄"} {meta?.label ?? dt} ({n})
              </Link>
            );
          })}
      </div>

      {/* Artifacts list */}
      <div className="rounded-xl bg-card border border-border-subtle overflow-hidden">
        {artifacts && artifacts.length > 0 ? (
          <div className="divide-y divide-border-subtle">
            {artifacts.map((artifact) => {
              const meta = DOMAIN_LABELS[artifact.domain_type];
              // Extract a meaningful preview from artifact_data
              const data = artifact.artifact_data as Record<string, any>;
              const narrative =
                data?.narrative ??
                data?.summary ??
                data?.answer ??
                data?.fullMarkdown?.slice(0, 100) ??
                "";
              const confidence = data?.confidence ?? data?.overallScore ?? null;

              return (
                <Link
                  key={artifact.id}
                  href={`/se-aas/artifacts/${artifact.id}`}
                  className="flex items-start gap-4 px-5 py-4 hover:bg-surface/50 transition-colors"
                >
                  <div className="w-9 h-9 rounded-lg bg-surface border border-border-subtle flex items-center justify-center text-lg flex-shrink-0 mt-0.5">
                    {meta?.icon ?? "📄"}
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1">
                      <span className="text-sm font-medium">{meta?.label ?? artifact.domain_type}</span>
                      <span className={`text-[10px] px-1.5 py-0.5 rounded font-mono bg-surface border border-border-subtle ${meta?.color ?? "text-muted"}`}>
                        {artifact.domain_type}
                      </span>
                      {confidence != null && (
                        <span className="ml-auto text-[10px] text-muted">
                          {typeof confidence === "number" && confidence <= 1
                            ? `${(confidence * 100).toFixed(0)}% confidence`
                            : `score ${confidence}`}
                        </span>
                      )}
                    </div>
                    {narrative && (
                      <p className="text-xs text-muted line-clamp-2 leading-relaxed">{narrative}</p>
                    )}
                    <div className="flex items-center gap-3 mt-1.5">
                      <span className="text-[10px] text-muted font-mono">
                        {artifact.id.slice(0, 8)}...
                      </span>
                      <span className="text-[10px] text-muted">
                        {new Date(artifact.created_at).toLocaleString("en-US", {
                          month: "short",
                          day: "numeric",
                          hour: "2-digit",
                          minute: "2-digit",
                        })}
                      </span>
                    </div>
                  </div>
                  <svg className="w-4 h-4 text-muted flex-shrink-0 mt-1" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
                  </svg>
                </Link>
              );
            })}
          </div>
        ) : (
          <div className="p-12">
            <EmptyState
              icon={
                <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m2.25 0H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" />
                </svg>
              }
              title={domainType ? `No ${DOMAIN_LABELS[domainType]?.label ?? domainType} artifacts` : "No artifacts yet"}
              description="Run any SE-AAS capability through the Copilot to generate your first artifact."
            />
          </div>
        )}
      </div>

      {/* Pagination */}
      {totalPages > 1 && (
        <div className="flex items-center justify-center gap-2">
          {page > 1 && (
            <Link
              href={`/se-aas/artifacts?${domainType ? `domainType=${domainType}&` : ""}page=${page - 1}`}
              className="px-3 py-1.5 rounded-lg border border-border-subtle text-xs hover:bg-surface transition-colors"
            >
              ← Previous
            </Link>
          )}
          <span className="text-xs text-muted">
            Page {page} of {totalPages}
          </span>
          {page < totalPages && (
            <Link
              href={`/se-aas/artifacts?${domainType ? `domainType=${domainType}&` : ""}page=${page + 1}`}
              className="px-3 py-1.5 rounded-lg border border-border-subtle text-xs hover:bg-surface transition-colors"
            >
              Next →
            </Link>
          )}
        </div>
      )}
    </div>
  );
}
