/**
 * AUTO-GENERATED — Do not edit manually.
 * Generated by: scripts/generate-stats.ts
 * Last updated: 2026-02-14T01:02:46.025Z
 *
 * These stats are computed from the actual codebase at build time.
 * To regenerate: npx tsx scripts/generate-stats.ts
 */

export const BRAIN_STATS = {
  brainRegions: 24,
  causalMethods: 9,
  passingTests: 2615,
  passingTestsFormatted: "2,615",
  testFiles: 94,
  connectors: 16,
  trainingPacks: 20,
  runtimeDeps: 0,
} as const;

export const BENCHMARK_RESULTS = {
  causalrivers: {
    bestAUROC: 0.8275,
    results: {
    "close_3": {
        "auroc": 0.8179,
        "varBaseline": 0.809,
        "delta": 0.0089
    },
    "close_5": {
        "auroc": 0.8047,
        "varBaseline": 0.806,
        "delta": -0.0013
    },
    "root_cause_3": {
        "auroc": 0.7954,
        "varBaseline": 0.788,
        "delta": 0.0074
    },
    "root_cause_5": {
        "auroc": 0.7514,
        "varBaseline": 0.751,
        "delta": 0.0004
    },
    "1_random_3": {
        "auroc": 0.8086,
        "varBaseline": 0.8,
        "delta": 0.0086
    },
    "1_random_5": {
        "auroc": 0.7965,
        "varBaseline": 0.793,
        "delta": 0.0035
    },
    "confounder_3": {
        "auroc": 0.7141,
        "varBaseline": 0.709,
        "delta": 0.0051
    },
    "confounder_5": {
        "auroc": 0.7232,
        "varBaseline": 0.722,
        "delta": 0.0012
    },
    "random_3": {
        "auroc": 0.8275,
        "varBaseline": 0.823,
        "delta": 0.0045
    },
    "random_5": {
        "auroc": 0.8038,
        "varBaseline": 0.801,
        "delta": 0.0028
    }
},
  },
  longmemeval: {
    overallAccuracy: 0.796,
    overallAccuracyFormatted: "79.6%",
    temporalReasoning: 0.849624060150376,
    temporalReasoningFormatted: "85.0%",
    typeAccuracies: {
    "temporal-reasoning": 85,
    "multi-session": 82,
    "knowledge-update": 75.6,
    "single-session-preference": 73.3,
    "single-session-assistant": 73.2,
    "single-session-user": 77.1
},
    totalQuestions: 500,
    totalCorrect: 398,
  },
} as const;
