/**
 * Template Performance Tracker
 *
 * Tracks how well each agent template performs and triggers
 * automatic evolution when performance drops below thresholds.
 *
 * Evolution flow:
 *   1. Template runs 10+ times with low success → shouldEvolveTemplate()
 *   2. LLM generates improved prompt variant
 *   3. A/B test: 50% traffic to each for 20 runs
 *   4. Winner promoted, loser archived
 *
 * RL integration:
 *   - Emits brain.templates.evolved signal with performance delta
 *   - Success/failure counts update after each agent execution
 */

import type { SupabaseClient } from "@supabase/supabase-js";
import { logger } from "@/lib/logger";

// ── Types ──────────────────────────────────────────────────────────────────

export interface TemplatePerformance {
  templateId: string;
  organizationId: string;
  totalRuns: number;
  successfulRuns: number;
  failedRuns: number;
  avgConfidence: number;
  successRate: number;
  evolutionStatus: string;
  lastEvolvedAt?: string;
}

export interface EvolutionResult {
  evolved: boolean;
  reason: string;
  variantTemplateId?: string;
  abTestId?: string;
}

// ── Evolution Thresholds ───────────────────────────────────────────────────

const MIN_RUNS_FOR_EVOLUTION = 10;
const LOW_SUCCESS_THRESHOLD = 0.6;
const LOW_CONFIDENCE_THRESHOLD = 0.5;
const AB_TEST_SAMPLE_SIZE = 20; // Runs per variant before concluding

// ── Core Functions ─────────────────────────────────────────────────────────

/**
 * Record a template execution result.
 * Updates usage_count, success/failure counts, and avg_confidence.
 */
export async function recordTemplateExecution(
  supabase: SupabaseClient,
  templateId: string,
  success: boolean,
  confidence: number,
): Promise<void> {
  try {
    // Get current stats
    const { data: template } = await supabase
      .from("agent_templates")
      .select("usage_count, success_count, failure_count, avg_confidence")
      .eq("id", templateId)
      .maybeSingle();

    if (!template) return;

    const usageCount = (template.usage_count || 0) + 1;
    const successCount = (template.success_count || 0) + (success ? 1 : 0);
    const failureCount = (template.failure_count || 0) + (success ? 0 : 1);

    // Exponential moving average for confidence
    const alpha = 0.3;
    const avgConfidence = template.avg_confidence
      ? alpha * confidence + (1 - alpha) * template.avg_confidence
      : confidence;

    await supabase
      .from("agent_templates")
      .update({
        usage_count: usageCount,
        success_count: successCount,
        failure_count: failureCount,
        avg_confidence: Math.round(avgConfidence * 1000) / 1000,
        last_used_at: new Date().toISOString(),
      })
      .eq("id", templateId);
  } catch (err) {
    logger.error("[TemplateTracker] Failed to record execution:", err);
  }
}

/**
 * Get performance metrics for a template.
 */
export async function getTemplatePerformance(
  supabase: SupabaseClient,
  templateId: string,
): Promise<TemplatePerformance | null> {
  const { data: template } = await supabase
    .from("agent_templates")
    .select("id, organization_id, usage_count, success_count, failure_count, avg_confidence, evolution_status")
    .eq("id", templateId)
    .maybeSingle();

  if (!template) return null;

  const totalRuns = (template.usage_count as number) || 0;
  const successfulRuns = (template.success_count as number) || 0;
  const failedRuns = (template.failure_count as number) || 0;

  return {
    templateId: template.id as string,
    organizationId: template.organization_id as string,
    totalRuns,
    successfulRuns,
    failedRuns,
    avgConfidence: (template.avg_confidence as number) || 0,
    successRate: totalRuns > 0 ? successfulRuns / totalRuns : 0,
    evolutionStatus: (template.evolution_status as string) || "stable",
  };
}

/**
 * Check if a template should evolve based on its performance.
 */
export function shouldEvolveTemplate(perf: TemplatePerformance): boolean {
  if (perf.totalRuns < MIN_RUNS_FOR_EVOLUTION) return false;
  if (perf.evolutionStatus === "evolving" || perf.evolutionStatus === "variant_testing") return false;
  if (perf.successRate < LOW_SUCCESS_THRESHOLD) return true;
  if (perf.avgConfidence < LOW_CONFIDENCE_THRESHOLD) return true;
  return false;
}

/**
 * Start template evolution: create a variant and begin A/B testing.
 *
 * Note: The variant's prompt improvement is generated by calling
 * the LLM with the original prompt + failure data. This function
 * creates the DB records for the A/B test.
 */
export async function evolveTemplate(
  supabase: SupabaseClient,
  templateId: string,
  improvedPrompt: string,
  organizationId: string,
): Promise<EvolutionResult> {
  try {
    // Get original template
    const { data: original } = await supabase
      .from("agent_templates")
      .select("*")
      .eq("id", templateId)
      .maybeSingle();

    if (!original) {
      return { evolved: false, reason: "Template not found" };
    }

    // Create variant template
    const { data: variant, error: variantError } = await supabase
      .from("agent_templates")
      .insert({
        organization_id: organizationId,
        name: `${original.name} (Evolved)`,
        description: `Auto-evolved variant of "${original.name}"`,
        command_id: original.command_id,
        prompt: improvedPrompt,
        gathering_schema: original.gathering_schema,
        agent_config: original.agent_config,
        is_public: false,
        source_template_id: templateId,
        variant_label: "B",
        evolution_status: "variant_testing",
      })
      .select("id")
      .single();

    if (variantError || !variant) {
      return { evolved: false, reason: `Failed to create variant: ${variantError?.message}` };
    }

    // Update original to mark as evolving
    await supabase
      .from("agent_templates")
      .update({
        evolution_status: "evolving",
        variant_label: "A",
      })
      .eq("id", templateId);

    // Create A/B test record
    const { data: abTest } = await supabase
      .from("template_ab_tests")
      .insert({
        original_template_id: templateId,
        variant_template_id: variant.id,
        organization_id: organizationId,
        status: "running",
      })
      .select("id")
      .single();

    // Emit RL signal
    await supabase.from("cross_domain_signals").insert({
      organization_id: organizationId,
      source_domain: "brain.templates",
      signal_type: "evolution_started",
      signal_value: 0.5,
      entity_type: "template_evolution",
      signal_metadata: {
        original_id: templateId,
        variant_id: variant.id,
        ab_test_id: abTest?.id,
        trigger: "low_performance",
      },
    });

    logger.warn(
      `[TemplateTracker] Evolution started: ${templateId} → ${variant.id} (A/B test: ${abTest?.id})`,
    );

    return {
      evolved: true,
      reason: "A/B test started",
      variantTemplateId: variant.id,
      abTestId: abTest?.id,
    };
  } catch (err) {
    logger.error("[TemplateTracker] Evolution failed:", err);
    return { evolved: false, reason: err instanceof Error ? err.message : "Unknown error" };
  }
}

/**
 * Get the template to use for execution, respecting active A/B tests.
 * If an A/B test is active, randomly selects original or variant (50/50).
 */
export async function getTemplateForExecution(
  supabase: SupabaseClient,
  templateId: string,
  organizationId: string,
): Promise<{ templateId: string; isVariant: boolean; abTestId?: string }> {
  // Check for active A/B test
  const { data: abTest } = await supabase
    .from("template_ab_tests")
    .select("id, original_template_id, variant_template_id")
    .eq("original_template_id", templateId)
    .eq("organization_id", organizationId)
    .eq("status", "running")
    .limit(1)
    .single();

  if (!abTest) {
    return { templateId, isVariant: false };
  }

  // 50/50 random split
  const useVariant = Math.random() > 0.5;

  return {
    templateId: useVariant
      ? (abTest.variant_template_id as string)
      : (abTest.original_template_id as string),
    isVariant: useVariant,
    abTestId: abTest.id as string,
  };
}

/**
 * Record an A/B test result and check if we should conclude.
 */
export async function recordABResult(
  supabase: SupabaseClient,
  abTestId: string,
  templateUsed: string,
  success: boolean,
): Promise<{ concluded: boolean; winner?: string }> {
  // Get test
  const { data: test } = await supabase
    .from("template_ab_tests")
    .select("*")
    .eq("id", abTestId)
    .single();

  if (!test || test.status !== "running") {
    return { concluded: false };
  }

  // Update counts
  const isOriginal = templateUsed === test.original_template_id;
  const updates: Record<string, unknown> = {};

  if (isOriginal) {
    const runs = ((test.original_runs as number) || 0) + 1;
    const currentSuccessRate = (test.original_success_rate as number) || 0;
    updates.original_runs = runs;
    updates.original_success_rate = currentSuccessRate * ((runs - 1) / runs) + (success ? 1 : 0) / runs;
  } else {
    const runs = ((test.variant_runs as number) || 0) + 1;
    const currentSuccessRate = (test.variant_success_rate as number) || 0;
    updates.variant_runs = runs;
    updates.variant_success_rate = currentSuccessRate * ((runs - 1) / runs) + (success ? 1 : 0) / runs;
  }

  await supabase
    .from("template_ab_tests")
    .update(updates)
    .eq("id", abTestId);

  // Check if we should conclude
  const originalRuns = isOriginal
    ? (updates.original_runs as number)
    : ((test.original_runs as number) || 0);
  const variantRuns = !isOriginal
    ? (updates.variant_runs as number)
    : ((test.variant_runs as number) || 0);

  if (originalRuns >= AB_TEST_SAMPLE_SIZE && variantRuns >= AB_TEST_SAMPLE_SIZE) {
    // Conclude the test
    const origRate = isOriginal
      ? (updates.original_success_rate as number)
      : ((test.original_success_rate as number) || 0);
    const varRate = !isOriginal
      ? (updates.variant_success_rate as number)
      : ((test.variant_success_rate as number) || 0);

    const winner = origRate >= varRate ? "original" : "variant";

    await supabase
      .from("template_ab_tests")
      .update({
        status: "completed",
        winner,
        completed_at: new Date().toISOString(),
      })
      .eq("id", abTestId);

    // Update template statuses
    const winnerId = winner === "original" ? test.original_template_id : test.variant_template_id;
    const loserId = winner === "original" ? test.variant_template_id : test.original_template_id;

    await supabase.from("agent_templates").update({ evolution_status: "stable" }).eq("id", winnerId);
    await supabase.from("agent_templates").update({ evolution_status: "archived_by_evolution" }).eq("id", loserId);

    // Emit RL signal
    await supabase.from("cross_domain_signals").insert({
      organization_id: test.organization_id,
      source_domain: "brain.templates",
      signal_type: "evolution_concluded",
      signal_value: Math.abs(origRate - varRate), // Performance delta
      entity_type: "template_evolution",
      signal_metadata: {
        ab_test_id: abTestId,
        winner,
        original_rate: origRate,
        variant_rate: varRate,
        delta: varRate - origRate,
      },
    });

    logger.warn(
      `[TemplateTracker] A/B test concluded: winner=${winner} (orig=${Math.round(origRate * 100)}%, variant=${Math.round(varRate * 100)}%)`,
    );

    return { concluded: true, winner };
  }

  return { concluded: false };
}
