#!/usr/bin/env tsx
/**
 * Native Agent Generator CLI
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * Scaffolds a new brain-native training agent from a template.
 *
 * Usage:
 *   # Interactive mode
 *   pnpm exec tsx scripts/agent-framework/create-native-agent.ts
 *
 *   # Direct mode
 *   pnpm exec tsx scripts/agent-framework/create-native-agent.ts \
 *     --name my-training-agent \
 *     --description "My custom training agent" \
 *     --schedule "0 2 * * 0" \
 *     --cpu 2048 \
 *     --memory 8192
 *
 * This generates:
 *   1. scripts/agents/{name}.ts — Agent implementation
 *   2. scripts/{name}-runner.ts — ECS runner script
 *   3. Auto-registers to AgentRegistry on import
 *
 * @packageDocumentation
 */

import * as readline from 'node:readline/promises';
import { writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';

// ============================================================================
// TYPES
// ============================================================================

interface AgentTemplate {
  name: string;
  description: string;
  version: string;
  schedule?: string;
  cpu: string;
  memory: string;
  tags: string[];
  enableLLM: boolean;
  enableBayesian: boolean;
  enableEmbedding: boolean;
  enableContrastive: boolean;
  enableImpactScoring: boolean;
  enableAnomalyMonitoring: boolean;
  enablePublicData: boolean;
}

// ============================================================================
// CLI HELPERS
// ============================================================================

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

async function prompt(question: string, defaultValue?: string): Promise<string> {
  const defaultHint = defaultValue ? ` (default: ${defaultValue})` : '';
  const answer = await rl.question(`${question}${defaultHint}: `);
  return answer.trim() || defaultValue || '';
}

async function promptBoolean(question: string, defaultValue: boolean = false): Promise<boolean> {
  const defaultHint = defaultValue ? ' (Y/n)' : ' (y/N)';
  const answer = await rl.question(`${question}${defaultHint}: `);
  const normalized = answer.trim().toLowerCase();
  if (!normalized) return defaultValue;
  return normalized === 'y' || normalized === 'yes';
}

// ============================================================================
// TEMPLATE GENERATION
// ============================================================================

function generateAgentImplementation(template: AgentTemplate): string {
  const className = template.name
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join('') + 'Agent';

  return `/**
 * ${template.description}
 *
 * Generated by: pnpm exec tsx scripts/agent-framework/create-native-agent.ts
 * Agent Type: Brain-Native Training Agent V5
 * Schedule: ${template.schedule || 'Manual only'}
 * Resources: ${template.cpu} CPU / ${template.memory} MB RAM
 */

import {
  BrainNativeAgent,
  type BrainNativeAgentConfig,
} from '../agent-framework/brain-native-agent-template';
import type { FetchResult, ConvertResult } from '../agent-framework/base-training-agent';
import type { ConnectorSignal } from '../../packages/memory-stack/src/connectors/connector-framework';
import type { TrainingPack } from '../../packages/memory-stack/src/learning/brain-trainer';

// ============================================================================
// ${template.name.toUpperCase()} AGENT
// ============================================================================

export class ${className} extends BrainNativeAgent {
  readonly name = '${template.name}';
  readonly version = '${template.version}';
  readonly description = '${template.description}';

  /**
   * STAGE 1: FETCH
   * ──────────────
   * Pull raw data from external sources (APIs, databases, files, etc.).
   *
   * TODO: Implement your data fetching logic here.
   * Examples:
   *   - Fetch from REST API (GitHub, FRED, etc.)
   *   - Query database (Postgres, MongoDB, etc.)
   *   - Read CSV/JSON files
   *   - Scrape web pages
   */
  async fetch(): Promise<FetchResult> {
    this.log('FETCH', 'Starting data fetch...');

    // TODO: Replace this stub with your actual fetch logic
    const data = {
      // Your raw data goes here
      // Example: { users: [...], transactions: [...] }
    };

    const sources = [
      // List of sources you fetched from
      // Example: 'GitHub API', 'FRED API', 'local CSV'
    ];

    const recordCount = 0; // TODO: Count records fetched

    this.log('FETCH', \`Fetched \${recordCount} records from \${sources.length} sources\`);

    return { data, sources, recordCount };
  }

  /**
   * STAGE 2: CONVERT
   * ────────────────
   * Transform raw data into brain-compatible formats.
   *
   * You must produce:
   *   1. ConnectorSignal[] — Time-series numeric signals for causal engine
   *   2. TrainingPack[] — Knowledge packs for brain trainer
   *
   * TODO: Implement your conversion logic here.
   */
  async convert(fetchResult: FetchResult): Promise<ConvertResult> {
    this.log('CONVERT', 'Converting data to brain format...');

    const signals: ConnectorSignal[] = [];
    const packs: TrainingPack[] = [];

    // TODO: Convert your raw data into signals
    // Example:
    // for (const record of fetchResult.data.records) {
    //   signals.push({
    //     organization_id: this.organizationId,
    //     source: '${template.name}',
    //     connector_type: '${template.name}',
    //     signal_type: 'your_metric_name',
    //     signal_value: record.value,
    //     signal_timestamp: new Date(record.timestamp),
    //     source_domain: 'your_domain',
    //     entity_type: 'your_entity_type',
    //     entity_id: record.id,
    //     metadata: { source: '${template.name}' },
    //   });
    // }

    // TODO: Build training packs for knowledge transfer
    // Example:
    // packs.push({
    //   id: '${template.name}_pack_1',
    //   title: 'Your Knowledge Pack',
    //   description: 'Knowledge about X causes Y',
    //   signals: signals.slice(0, 100),
    //   expectedCausalEdges: [
    //     {
    //       sourceDomain: 'domain_a',
    //       targetDomain: 'domain_b',
    //       hypothesizedLag: 7,
    //       expectedEffectSize: 0.3,
    //       explanation: 'Because X, then Y after 7 days',
    //     },
    //   ],
    //   expectedPatterns: [],
    //   expectedRules: [],
    // });

    this.log('CONVERT', \`Generated \${signals.length} signals + \${packs.length} training packs\`);

    return { signals, packs };
  }
}

// ──────────────────────────────────────────────────────────────────────────
// AUTO-REGISTRATION
// ──────────────────────────────────────────────────────────────────────────
// This agent self-registers to the global registry when imported.
// No manual registry.register() needed!

${className}.registerAgent({
  name: '${template.name}',
  description: '${template.description}',
  version: '${template.version}',
  ${template.schedule ? `schedule: '${template.schedule}',` : ''}
  resourceRequirements: {
    cpu: '${template.cpu}',
    memory: '${template.memory}',
  },
  tags: [${template.tags.map(t => `'${t}'`).join(', ')}],
});
`;
}

function generateRunnerScript(template: AgentTemplate): string {
  const className = template.name
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join('') + 'Agent';

  return `#!/usr/bin/env tsx
/**
 * ${template.description} — ECS Runner
 *
 * Standalone entry point for the ${template.name} agent.
 * Designed to run as an ECS Fargate task (one-shot).
 *
 * Usage:
 *   # Full run
 *   pnpm exec tsx scripts/${template.name}-runner.ts
 *
 *   # Dry-run (no persistence)
 *   DRY_RUN=true pnpm exec tsx scripts/${template.name}-runner.ts
 *
 * Environment Variables:
 *   SUPABASE_URL              — Required
 *   SUPABASE_SERVICE_ROLE_KEY — Required
 *   DRY_RUN                   — Optional (true = no persist)
 *   VERBOSE                   — Optional (true = detailed logs)
 *   ${template.enableLLM ? 'ANTHROPIC_API_KEY or OPENAI_API_KEY — Optional (for LLM amplifier)' : ''}
 */

import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

// ── Load .env (zero-dependency pattern) ──
function loadEnv(): void {
  try {
    const envPath = resolve(import.meta.dirname || __dirname, '..', '.env');
    const content = readFileSync(envPath, 'utf-8');
    for (const line of content.split('\\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const eqIndex = trimmed.indexOf('=');
      if (eqIndex === -1) continue;
      const key = trimmed.substring(0, eqIndex).trim();
      const value = trimmed.substring(eqIndex + 1).trim();
      if (!process.env[key]) {
        process.env[key] = value;
      }
    }
  } catch {
    // .env file not found — rely on environment variables (expected in ECS)
  }
}
loadEnv();

// ── Imports (after env loaded) ──
import { AgentRegistry } from './agent-framework/agent-registry';
import { AgentManager } from './agent-framework/agent-manager';
import { ${className} } from './agents/${template.name}';

// ── Configuration ──
const ORGANIZATION_ID = process.env.ORGANIZATION_ID || '00000000-0000-4000-a000-000000000001';
const DRY_RUN = process.env.DRY_RUN === 'true';
const VERBOSE = process.env.VERBOSE === 'true';

async function main(): Promise<void> {
  const startTime = Date.now();

  console.log('════════════════════════════════════════════════════════════');
  console.log(\`  ${template.description}\`);
  console.log(\`  Started: \${new Date().toISOString()}\`);
  console.log(\`  Mode: \${DRY_RUN ? 'DRY RUN' : 'PRODUCTION'}\`);
  console.log(\`  Verbose: \${VERBOSE ? 'YES' : 'NO'}\`);
  console.log('════════════════════════════════════════════════════════════\\n');

  // Validate required env vars
  const supabaseUrl = process.env.SUPABASE_URL;
  const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!supabaseUrl || !supabaseKey) {
    console.error('ERROR: Missing required environment variables:');
    if (!supabaseUrl) console.error('  - SUPABASE_URL');
    if (!supabaseKey) console.error('  - SUPABASE_SERVICE_ROLE_KEY');
    console.error('\\nSet these in .env or as environment variables.');
    process.exit(1);
  }

  // ── Set up registry + manager ──
  const registry = new AgentRegistry();

  // Agent is already registered via auto-registration!
  // Just import the agent file to trigger registration.

  const manager = new AgentManager(registry, {
    supabaseUrl,
    supabaseKey,
    organizationId: ORGANIZATION_ID,
  });

  // ── Print registry ──
  registry.printSummary();

  // ── Run the agent ──
  try {
    const result = await manager.runWithRetry('${template.name}', 2, {
      dryRun: DRY_RUN,
      verbose: VERBOSE,
      ${template.enableLLM ? 'enableLLMAmplifier: true,' : ''}
      ${template.enableBayesian ? 'enableBayesian: true,' : ''}
      ${template.enableEmbedding ? 'enableEmbedding: true,' : ''}
      ${template.enableContrastive ? 'enableContrastive: true,' : ''}
      ${template.enableImpactScoring ? 'enableImpactScoring: true,' : ''}
      ${template.enableAnomalyMonitoring ? 'enableAnomalyMonitoring: true,' : ''}
      ${template.enablePublicData ? 'enablePublicData: true,' : ''}
    });

    const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);

    console.log('\\n════════════════════════════════════════════════════════════');
    console.log(\`  ${template.description} — Run Complete\`);
    console.log('════════════════════════════════════════════════════════════');
    console.log(\`  Duration:    \${elapsed}s\`);
    console.log(\`  Signals:     \${result.signalsGenerated}\`);
    console.log(\`  Packs:       \${result.packsProcessed}\`);
    console.log(\`  Errors:      \${result.errorsEncountered.length}\`);
    console.log(\`  Summary:     \${result.summary}\`);

    if (result.errorsEncountered.length > 0) {
      console.log('\\n  Errors:');
      for (const err of result.errorsEncountered) {
        console.log(\`    - \${err}\`);
      }
    }

    console.log('════════════════════════════════════════════════════════════\\n');

    // Exit with appropriate code
    process.exit(result.errorsEncountered.length > 0 ? 1 : 0);
  } catch (err) {
    const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);
    console.error(\`\\n[FATAL] ${template.description} failed after \${elapsed}s:\`);
    console.error(err instanceof Error ? err.message : String(err));
    process.exit(2);
  }
}

// ── Entry point ──
main().catch((err) => {
  console.error('[FATAL] Unhandled error:', err);
  process.exit(2);
});
`;
}

// ============================================================================
// MAIN CLI
// ============================================================================

async function main() {
  console.log('\n═══════════════════════════════════════════════════════════');
  console.log('  NexusBrain Native Agent Generator V5');
  console.log('═══════════════════════════════════════════════════════════\n');

  // Parse CLI args
  const args = process.argv.slice(2);
  const getArg = (flag: string): string | undefined => {
    const idx = args.indexOf(flag);
    return idx >= 0 && idx + 1 < args.length ? args[idx + 1] : undefined;
  };
  const hasArg = (flag: string): boolean => args.includes(flag);

  let template: AgentTemplate;

  if (hasArg('--name')) {
    // Direct mode (non-interactive)
    template = {
      name: getArg('--name') || '',
      description: getArg('--description') || '',
      version: getArg('--version') || '1.0.0',
      schedule: getArg('--schedule'),
      cpu: getArg('--cpu') || '2048',
      memory: getArg('--memory') || '8192',
      tags: (getArg('--tags') || 'training').split(','),
      enableLLM: hasArg('--enable-llm'),
      enableBayesian: hasArg('--enable-bayesian'),
      enableEmbedding: hasArg('--enable-embedding'),
      enableContrastive: hasArg('--enable-contrastive'),
      enableImpactScoring: hasArg('--enable-impact-scoring'),
      enableAnomalyMonitoring: hasArg('--enable-anomaly-monitoring'),
      enablePublicData: hasArg('--enable-public-data'),
    };
  } else {
    // Interactive mode
    console.log('Answer the following questions to scaffold your agent:\n');

    const name = await prompt('Agent name (kebab-case, e.g., my-training-agent)', 'my-training-agent');
    const description = await prompt('Description (one sentence)', 'My custom training agent');
    const version = await prompt('Version', '1.0.0');
    const schedule = await prompt('Cron schedule (optional, e.g., "0 2 * * 0" for Sunday 2 AM)', '');
    const cpu = await prompt('CPU (in MB, e.g., 2048 for 2 vCPU)', '2048');
    const memory = await prompt('Memory (in MB, e.g., 8192 for 8 GB)', '8192');
    const tagsRaw = await prompt('Tags (comma-separated, e.g., training,github)', 'training');
    const tags = tagsRaw.split(',').map(t => t.trim());

    console.log('\nBrain Region Integrations (enable Y/n):');
    const enableLLM = await promptBoolean('  Enable LLM Brain Amplifier (requires API key)?', false);
    const enableBayesian = await promptBoolean('  Enable Bayesian Weight Updates (Hippocampus)?', true);
    const enableEmbedding = await promptBoolean('  Enable Embedding Fine-Tuning (Neocortex)?', true);
    const enableContrastive = await promptBoolean('  Enable Contrastive Causal Learning (PFC)?', true);
    const enableImpactScoring = await promptBoolean('  Enable Impact Scoring (Amygdala)?', true);
    const enableAnomalyMonitoring = await promptBoolean('  Enable Anomaly Monitoring (Insula)?', true);
    const enablePublicData = await promptBoolean('  Enable Public Data Learning (Sensory Cortex)?', false);

    template = {
      name,
      description,
      version,
      schedule,
      cpu,
      memory,
      tags,
      enableLLM,
      enableBayesian,
      enableEmbedding,
      enableContrastive,
      enableImpactScoring,
      enableAnomalyMonitoring,
      enablePublicData,
    };
  }

  // Validate
  if (!template.name) {
    console.error('ERROR: Agent name is required.');
    process.exit(1);
  }

  // Generate files
  const agentFile = resolve(__dirname, '../agents', `${template.name}.ts`);
  const runnerFile = resolve(__dirname, '..', `${template.name}-runner.ts`);

  if (existsSync(agentFile)) {
    console.error(`\nERROR: Agent file already exists: ${agentFile}`);
    console.error('Choose a different name or delete the existing file.');
    process.exit(1);
  }

  if (existsSync(runnerFile)) {
    console.error(`\nERROR: Runner file already exists: ${runnerFile}`);
    console.error('Choose a different name or delete the existing file.');
    process.exit(1);
  }

  console.log('\n──────────────────────────────────────────────────────────');
  console.log('Generating files...\n');

  const agentCode = generateAgentImplementation(template);
  const runnerCode = generateRunnerScript(template);

  writeFileSync(agentFile, agentCode, 'utf-8');
  writeFileSync(runnerFile, runnerCode, 'utf-8');

  console.log(`✓ Created: ${agentFile}`);
  console.log(`✓ Created: ${runnerFile}`);

  console.log('\n──────────────────────────────────────────────────────────');
  console.log('Next steps:\n');
  console.log(`1. Implement fetch() and convert() in: ${agentFile}`);
  console.log(`2. Test locally:  pnpm exec tsx ${runnerFile}`);
  console.log(`3. Deploy to ECS: ./infra/run-task.sh ${template.name}`);
  console.log('\nYour agent is now auto-registered and ready to run!');
  console.log('═══════════════════════════════════════════════════════════\n');

  rl.close();
  process.exit(0);
}

main().catch((err) => {
  console.error('[FATAL]', err);
  process.exit(1);
});
