-- ============================================================================
-- Cascade Alerts Table
--
-- Stores cascade alerts generated by the anomaly monitor → cascade alert pipeline.
-- Enables audit trails, feedback loops, and verification of predicted cascades.
-- ============================================================================

CREATE TABLE IF NOT EXISTS cascade_alerts (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  organization_id UUID NOT NULL,
  alert_id TEXT NOT NULL,
  severity TEXT NOT NULL CHECK (severity IN ('critical', 'high', 'medium', 'low')),
  trigger_domain TEXT NOT NULL,
  trigger_signal_type TEXT NOT NULL,
  anomaly_score NUMERIC NOT NULL,
  predicted_path TEXT[] NOT NULL,
  expected_impacts JSONB NOT NULL DEFAULT '[]',
  recommended_interventions JSONB NOT NULL DEFAULT '[]',
  -- Verification / feedback loop fields
  verified_at TIMESTAMPTZ,
  actual_propagation JSONB,
  prediction_accuracy NUMERIC,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_cascade_alerts_org
  ON cascade_alerts (organization_id);
CREATE INDEX IF NOT EXISTS idx_cascade_alerts_severity
  ON cascade_alerts (organization_id, severity);
CREATE INDEX IF NOT EXISTS idx_cascade_alerts_created
  ON cascade_alerts (organization_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cascade_alerts_unverified
  ON cascade_alerts (organization_id)
  WHERE verified_at IS NULL;

-- RLS
ALTER TABLE cascade_alerts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "service_role_all" ON cascade_alerts FOR ALL
  USING (auth.role() = 'service_role');
