-- ============================================================================
-- LLM Brain Amplifier Columns
--
-- Adds columns across existing tables for storing LLM-generated semantic
-- enrichment from the Brain Amplifier module.
--
-- 5 Gap Areas:
--   Gap 1 (ai_memory)                       — Insight amplification
--   Gap 2 (cascade_alerts)                   — Anomaly interpretation
--   Gap 3 (prediction_records)               — Prediction verification verdict
--   Gap 4 (causal_relationships_statistical) — Causal mechanism hypotheses
--   Gap 5 (brain_daily_snapshots)            — Executive consolidation briefing
-- ============================================================================

-- Gap 3: LLM Prediction Verification
-- Stores nuanced verdict beyond the binary direction+magnitude check
ALTER TABLE prediction_records ADD COLUMN IF NOT EXISTS llm_verdict TEXT;
ALTER TABLE prediction_records ADD COLUMN IF NOT EXISTS llm_reasoning TEXT;
ALTER TABLE prediction_records ADD COLUMN IF NOT EXISTS llm_confidence_adjustment NUMERIC;

-- Gap 4: Causal Mechanism Hypothesis
-- "Why does A cause B?" — generated by Claude for newly discovered edges
ALTER TABLE causal_relationships_statistical ADD COLUMN IF NOT EXISTS mechanism_hypothesis TEXT;
ALTER TABLE causal_relationships_statistical ADD COLUMN IF NOT EXISTS llm_confounders TEXT[];
ALTER TABLE causal_relationships_statistical ADD COLUMN IF NOT EXISTS testable_implications TEXT[];

-- Gap 2: Anomaly Interpretation
-- Semantic context for statistical anomalies detected by the anomaly monitor
ALTER TABLE cascade_alerts ADD COLUMN IF NOT EXISTS llm_interpretation TEXT;
ALTER TABLE cascade_alerts ADD COLUMN IF NOT EXISTS llm_likely_causes TEXT[];
ALTER TABLE cascade_alerts ADD COLUMN IF NOT EXISTS llm_suggested_actions TEXT[];

-- Gap 5: Executive Consolidation Briefing
-- CTO-grade daily briefing from the nightly consolidation cycle
ALTER TABLE brain_daily_snapshots ADD COLUMN IF NOT EXISTS executive_summary TEXT;
ALTER TABLE brain_daily_snapshots ADD COLUMN IF NOT EXISTS key_findings JSONB DEFAULT '[]';
ALTER TABLE brain_daily_snapshots ADD COLUMN IF NOT EXISTS strategic_implications JSONB DEFAULT '[]';

-- Gap 1: Insight Amplification
-- Business-readable narratives for DMN-discovered insights
ALTER TABLE ai_memory ADD COLUMN IF NOT EXISTS llm_explanation TEXT;
ALTER TABLE ai_memory ADD COLUMN IF NOT EXISTS llm_business_impact TEXT;
ALTER TABLE ai_memory ADD COLUMN IF NOT EXISTS llm_recommended_actions JSONB DEFAULT '[]';
