-- Memory & Context Container: Add context tracking columns to conversations
-- Enables the MemoryUsageIndicator and context-cleanup agent.

ALTER TABLE conversations
  ADD COLUMN IF NOT EXISTS token_count    INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS context_summary JSONB;

COMMENT ON COLUMN conversations.token_count IS
  'Estimated cumulative token usage for this conversation (updated by chat API on each turn)';

COMMENT ON COLUMN conversations.context_summary IS
  'Compressed context summary generated by cleanup agent when token_count exceeds threshold. '
  'Structure: { summary: string, summarized_at: ISO8601, messages_collapsed: number, original_token_count: number }';
