/**
 * Overnight Agent Executor
 * ========================
 * Executes a single "code-agent" child job:
 *   1. Generate a branch name
 *   2. Ask Claude (haiku) to generate code files for the ticket
 *   3. Create the GitHub branch
 *   4. Commit generated files
 *   5. Open a PR
 *   6. Request a review from the most recent committer
 *   7. Send a Slack notification (non-fatal)
 *   8. Record RL outcome
 *
 * Called from processSeAaSJobs when task_type = "code-agent".
 */

import type { SupabaseClient } from "@supabase/supabase-js";
import Anthropic from "@anthropic-ai/sdk";
import { logger } from "@/lib/logger";
import {
  createGitHubBranch,
  commitFilesToBranch,
  createGitHubPR,
} from "@/lib/connectors/writeback/github";
import type { GitHubFileToCommit } from "@/lib/connectors/writeback/github";
import { postSlackMessage } from "@/lib/connectors/writeback/slack";
import { recordAgentOutcome } from "@/lib/brain/agent-rl";
import { startJobHeartbeat, stopJobHeartbeat } from "@/lib/se-aas/job-heartbeat";

// ── Types ────────────────────────────────────────────────────────────────────

export interface CodeAgentTicket {
  title: string;
  description: string;
  type: string;
  priority: string;
  estimate: string;
  domain: string;
}

export interface CodeAgentPayload {
  ticket: CodeAgentTicket;
  repoOwner: string;
  repoName: string;
  githubToken: string;
  slackToken?: string;
  slackChannel?: string;
  parentJobId: string;
  brainContext?: string;
}

export interface CodeAgentResult {
  success: boolean;
  prUrl?: string;
  prNumber?: number;
  filesCommitted?: number;
  branchName?: string;
  error?: string;
}

// ── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Slugify a string for use in branch names.
 * Lowercase, replace spaces/special chars with dashes, trim dashes.
 */
function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-{2,}/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
}

/**
 * Build the PR body markdown with ticket details and agent attribution.
 */
function buildPRBody(ticket: CodeAgentTicket, orgId: string): string {
  return `## ${ticket.title}

**Type:** ${ticket.type}
**Priority:** ${ticket.priority}
**Estimate:** ${ticket.estimate}
**Domain:** ${ticket.domain}

### Description

${ticket.description}

---

> Generated by [BrainOS Overnight Agent](https://platform.usebrainos.com) for workspace \`${orgId}\`
>
> This PR was automatically created. Please review carefully before merging.`;
}

const GITHUB_API_BASE = "https://api.github.com";
const GITHUB_TIMEOUT_MS = 30_000;

/**
 * Fetch most recent committer login from GitHub.
 * Returns null if the request fails (non-fatal).
 */
async function getMostRecentCommitter(
  token: string,
  owner: string,
  repo: string
): Promise<string | null> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), GITHUB_TIMEOUT_MS);

  try {
    const response = await fetch(
      `${GITHUB_API_BASE}/repos/${owner}/${repo}/commits?per_page=1`,
      {
        method: "GET",
        signal: controller.signal,
        headers: {
          Accept: "application/vnd.github+json",
          Authorization: `Bearer ${token}`,
          "X-GitHub-Api-Version": "2022-11-28",
        },
      }
    );

    if (!response.ok) return null;

    const data = await response.json() as unknown[];
    const firstCommit = data[0] as Record<string, unknown> | undefined;
    const author = firstCommit?.author as Record<string, unknown> | undefined;
    return typeof author?.login === "string" ? author.login : null;
  } catch {
    return null;
  } finally {
    clearTimeout(timer);
  }
}

/**
 * Request a review on a PR. Non-fatal — logs warning on failure.
 */
async function requestPRReview(
  token: string,
  owner: string,
  repo: string,
  prNumber: number,
  reviewerLogin: string
): Promise<void> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), GITHUB_TIMEOUT_MS);

  try {
    const response = await fetch(
      `${GITHUB_API_BASE}/repos/${owner}/${repo}/pulls/${prNumber}/requested_reviewers`,
      {
        method: "POST",
        signal: controller.signal,
        headers: {
          "Content-Type": "application/json",
          Accept: "application/vnd.github+json",
          Authorization: `Bearer ${token}`,
          "X-GitHub-Api-Version": "2022-11-28",
        },
        body: JSON.stringify({ reviewers: [reviewerLogin] }),
      }
    );

    if (!response.ok) {
      const text = await response.text();
      logger.warn("[overnight-executor] requestPRReview failed", {
        status: response.status,
        body: text.slice(0, 200),
      });
    }
  } catch (err) {
    logger.warn("[overnight-executor] requestPRReview error (non-fatal):", err);
  } finally {
    clearTimeout(timer);
  }
}

// ── Main executor ─────────────────────────────────────────────────────────────

/**
 * Execute a single code-agent job.
 *
 * @param supabase   - Service-role Supabase client
 * @param jobId      - The agent_queue job ID for RL recording
 * @param orgId      - Organisation ID (for RL + scoping)
 * @param payload    - Full CodeAgentPayload from agent_queue.payload
 */
export async function executeCodeAgentJob(
  supabase: SupabaseClient,
  jobId: string,
  orgId: string,
  payload: CodeAgentPayload
): Promise<CodeAgentResult> {
  const startMs = Date.now();
  const { ticket, repoOwner, repoName, githubToken, slackToken, slackChannel, brainContext } = payload;

  // ── Heartbeat: prevent stale-job watchdog from killing long-running code-agent jobs ──
  // Code-agent jobs can take 2–5 minutes (branch + codegen + PR). The watchdog
  // threshold is 120s. Heartbeat every 30s gives 3 grace beats.
  const heartbeatHandle = startJobHeartbeat(supabase, jobId);

  try {
  // ── Step 1: Generate branch name ─────────────────────────────────────
  const sluggedTitle = slugify(ticket.title);
  const suffix = Date.now().toString(36);
  const branchName = `agent/${sluggedTitle}-${suffix}`;

  logger.warn("[overnight-executor] Starting code-agent job", {
    jobId,
    orgId,
    branchName,
    repo: `${repoOwner}/${repoName}`,
  });

  // ── Step 2: Ask Claude (haiku) to generate code files ────────────────
  let generatedFiles: GitHubFileToCommit[] = [];

  try {
    const apiKey = process.env.ANTHROPIC_API_KEY ?? "";
    if (!apiKey) throw new Error("ANTHROPIC_API_KEY not available");

    const anthropic = new Anthropic({ apiKey });

    const systemPrompt = `You are a senior software engineer implementing a ticket.

Ticket: ${ticket.title}
Description: ${ticket.description}
Domain: ${ticket.domain}
Estimate: ${ticket.estimate}
${brainContext ? `Codebase Context:\n${brainContext}` : ""}

Generate the implementation as a JSON array of files:
[{ "path": "relative/path/to/file.ts", "content": "...full file content..." }]

Rules:
- Max 5 files per ticket
- Use TypeScript. Match existing codebase patterns from context if available.
- Include the primary implementation + a test file
- Return ONLY the JSON array, no markdown fences`;

    const response = await anthropic.messages.create({
      model: "claude-haiku-4-5-20251001",
      max_tokens: 8192,
      system: systemPrompt,
      messages: [
        {
          role: "user",
          content: `Implement this ticket: ${ticket.title}\n\nDescription: ${ticket.description}`,
        },
      ],
    });

    const rawText =
      response.content[0]?.type === "text" ? response.content[0].text : "[]";

    // Strip markdown fences if Claude wrapped the JSON
    const stripped = rawText
      .replace(/^```(?:json)?\s*/i, "")
      .replace(/\s*```\s*$/i, "")
      .trim();

    try {
      const parsed = JSON.parse(stripped);
      if (Array.isArray(parsed)) {
        generatedFiles = (parsed as Array<Record<string, unknown>>)
          .filter(
            (f) =>
              typeof f.path === "string" &&
              typeof f.content === "string" &&
              f.path.length > 0
          )
          .slice(0, 5)
          .map((f) => ({ path: f.path as string, content: f.content as string }));
      }
    } catch (parseErr) {
      logger.warn("[overnight-executor] Failed to parse Claude file response", {
        jobId,
        parseErr,
        rawText: rawText.slice(0, 500),
      });
    }
  } catch (claudeErr) {
    logger.warn("[overnight-executor] Claude code generation failed (continuing with placeholder)", {
      jobId,
      error: claudeErr instanceof Error ? claudeErr.message : String(claudeErr),
    });
  }

  // ── Step 3: Check OpenClaw gateway (non-fatal static analysis) ────────
  const openclawUrl = process.env.OPENCLAW_GATEWAY_URL;
  if (openclawUrl && generatedFiles.length > 0) {
    try {
      const ocResponse = await fetch(`${openclawUrl}/analyze`, {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${process.env.OPENCLAW_API_KEY ?? ""}` },
        body: JSON.stringify({ files: generatedFiles, context: `${repoOwner}/${repoName}` }),
        signal: AbortSignal.timeout(15_000),
      });
      if (ocResponse.ok) {
        const ocResult = await ocResponse.json() as Record<string, unknown>;
        logger.warn("[overnight-executor] OpenClaw analysis complete", {
          jobId,
          issues: ocResult.issues ?? "none",
          score: ocResult.score ?? "n/a",
        });
      }
    } catch (ocErr) {
      logger.warn("[overnight-executor] OpenClaw analysis skipped (non-fatal):", ocErr);
    }
  }

  // ── Step 4: Create GitHub branch (hard failure if branch creation fails) ─
  try {
    await createGitHubBranch(githubToken, repoOwner, repoName, branchName);
  } catch (branchErr) {
    const errMsg = branchErr instanceof Error ? branchErr.message : String(branchErr);
    logger.error("[overnight-executor] Branch creation failed (hard failure)", { jobId, branchName, error: errMsg });

    await recordAgentOutcome(supabase, {
      agentId: jobId,
      domain: "code-agent",
      taskDescription: `Create branch for: ${ticket.title}`,
      resultSummary: `Branch creation failed: ${errMsg}`,
      quality: 0,
      executionMs: Date.now() - startMs,
      organizationId: orgId,
      userId: "agent",
    });

    return { success: false, error: `Branch creation failed: ${errMsg}` };
  }

  // ── Step 5: Commit files to branch ───────────────────────────────────
  // If Claude generated no files, create a placeholder markdown file
  const filesToCommit: GitHubFileToCommit[] =
    generatedFiles.length > 0
      ? generatedFiles
      : [
          {
            path: `agent-notes/${sluggedTitle}.md`,
            content: `# ${ticket.title}\n\n${ticket.description}\n\n*Generated by BrainOS Overnight Agent — manual implementation required.*\n`,
          },
        ];

  try {
    await commitFilesToBranch(
      githubToken,
      repoOwner,
      repoName,
      branchName,
      filesToCommit,
      `feat: ${ticket.title} [agent-generated]`
    );
  } catch (commitErr) {
    const errMsg = commitErr instanceof Error ? commitErr.message : String(commitErr);
    logger.error("[overnight-executor] File commit failed", { jobId, branchName, error: errMsg });

    await recordAgentOutcome(supabase, {
      agentId: jobId,
      domain: "code-agent",
      taskDescription: `Commit files for: ${ticket.title}`,
      resultSummary: `Commit failed: ${errMsg}`,
      quality: 0.1,
      executionMs: Date.now() - startMs,
      organizationId: orgId,
      userId: "agent",
    });

    return { success: false, error: `File commit failed: ${errMsg}`, branchName };
  }

  // ── Step 6: Open PR ───────────────────────────────────────────────────
  let prResult: { number: number; url: string; title: string } | null = null;

  try {
    prResult = await createGitHubPR(
      githubToken,
      repoOwner,
      repoName,
      ticket.title,
      buildPRBody(ticket, orgId),
      branchName
    );
  } catch (prErr) {
    const errMsg = prErr instanceof Error ? prErr.message : String(prErr);
    logger.error("[overnight-executor] PR creation failed", { jobId, branchName, error: errMsg });

    await recordAgentOutcome(supabase, {
      agentId: jobId,
      domain: "code-agent",
      taskDescription: `Open PR for: ${ticket.title}`,
      resultSummary: `PR creation failed: ${errMsg}`,
      quality: 0.2,
      executionMs: Date.now() - startMs,
      organizationId: orgId,
      userId: "agent",
    });

    return {
      success: false,
      error: `PR creation failed: ${errMsg}`,
      branchName,
      filesCommitted: filesToCommit.length,
    };
  }

  // ── Step 7: Find reviewer via git blame (most recent committer) ───────
  const reviewerLogin = await getMostRecentCommitter(githubToken, repoOwner, repoName);

  // ── Step 8: Request review on PR (non-fatal) ──────────────────────────
  if (reviewerLogin && prResult) {
    await requestPRReview(githubToken, repoOwner, repoName, prResult.number, reviewerLogin);
  }

  // ── Step 9: Slack notification (non-fatal) ────────────────────────────
  if (slackToken && slackChannel && prResult) {
    const slackBlocks = [
      {
        type: "header",
        text: {
          type: "plain_text",
          text: "Agent opened a PR for review",
          emoji: false,
        },
      },
      {
        type: "section",
        fields: [
          {
            type: "mrkdwn",
            text: `*Ticket:*\n${ticket.title}`,
          },
          {
            type: "mrkdwn",
            text: `*PR:*\n<${prResult.url}|View Pull Request>`,
          },
          ...(reviewerLogin
            ? [
                {
                  type: "mrkdwn",
                  text: `*Reviewer:*\n@${reviewerLogin}`,
                },
              ]
            : []),
          {
            type: "mrkdwn",
            text: `*Branch:*\n\`${branchName}\``,
          },
        ],
      },
      {
        type: "context",
        elements: [
          {
            type: "mrkdwn",
            text: `Generated by BrainOS Overnight Agent | ${new Date().toISOString().slice(0, 10)}`,
          },
        ],
      },
    ];

    const slackResult = await postSlackMessage(slackToken, {
      channel: slackChannel,
      text: `Agent opened a PR: ${ticket.title} — ${prResult.url}`,
      blocks: slackBlocks,
    });

    if (!slackResult.success) {
      logger.warn("[overnight-executor] Slack notification failed (non-fatal)", {
        jobId,
        error: slackResult.error,
      });
    }
  }

  // ── Step 10: Record RL outcome ────────────────────────────────────────
  const quality = prResult ? 0.8 : 0.3;

  await recordAgentOutcome(supabase, {
    agentId: jobId,
    domain: "code-agent",
    taskDescription: `Implement ticket: ${ticket.title}`,
    resultSummary: prResult
      ? `PR #${prResult.number} opened: ${prResult.url} (${filesToCommit.length} files committed)`
      : "Partial: branch + files committed but PR failed",
    quality,
    executionMs: Date.now() - startMs,
    organizationId: orgId,
    userId: "agent",
  });

  logger.warn("[overnight-executor] Code-agent job complete", {
    jobId,
    orgId,
    branchName,
    prNumber: prResult?.number,
    prUrl: prResult?.url,
    filesCommitted: filesToCommit.length,
    durationMs: Date.now() - startMs,
  });

  return {
    success: true,
    prUrl: prResult?.url,
    prNumber: prResult?.number,
    filesCommitted: filesToCommit.length,
    branchName,
  };
  } finally {
    // Always stop heartbeat — interval must never leak after job completes or throws
    stopJobHeartbeat(heartbeatHandle);
  }
}
