/**
 * Copilot Post-Flight
 *
 * Handles all fire-and-forget persistence that runs after the SSE stream finishes:
 *   1. RL quality computation + outcome recording
 *   2. Decision pattern training (ai_memory upsert + cross_domain_signals)
 *   3. Response harvesting (Haiku-powered key fact extraction → ai_memory)
 *   4. MoA post-stream synthesis storage (when _useMoA flag is set)
 *   5. Chat auto-save to the conversations table
 *   6. Tier-1 raw knowledge store ingest (both user + assistant turns)
 *   7. Mem0 structured fact extraction
 *
 * All operations are fire-and-forget: errors are logged but NEVER propagate.
 * The calling code must ensure the SSE stream is already closed before calling
 * runPostFlight (or it can be called concurrently in a void promise).
 */

import { logger } from "@/lib/logger";
import type { CopilotExecutionContext } from "@/lib/copilot/execution-context";

export interface PostFlightOptions {
  ctx: CopilotExecutionContext;
  streamedAssistantText: string;
  detectedIntent: string | null;
  v4SmartModel: string;
  streamStartMs: number;
  seaasResult: Record<string, unknown> | null;
  accountingResult: Record<string, unknown> | null;
  deliveryIntelligenceResult: Record<string, unknown> | null;
  /** Whether Self-MoA was activated for this request */
  useMoA: boolean;
  /** Effective system prompt sent to the LLM (needed for MoA re-sampling) */
  effectiveSystemPrompt: string;
  /** Causal weights snapshot taken before the stream (for federation delta) */
  copilotCausalWeightsBefore: Map<string, number>;
  copilotFedCycleId: string;
  /** Whether the 5-min federation delta TTL has elapsed for this org */
  shouldRunFederationDelta: boolean;
  /** Stable UUID generated by the client for the current chat session — used to upsert conversations */
  conversationId?: string;
  /** ADR-028: IDs of capability_library tools injected via working-memory CRAFT retrieval */
  toolLibraryIds?: string[];
}

/**
 * Run all post-flight persistence tasks.
 *
 * This function is designed to be called with `void runPostFlight(opts)` — it
 * swallows all errors and never throws.
 */
export async function runPostFlight(opts: PostFlightOptions): Promise<void> {
  const {
    ctx,
    conversationId: _conversationId,
    streamedAssistantText,
    detectedIntent,
    v4SmartModel,
    streamStartMs,
    seaasResult,
    accountingResult,
    deliveryIntelligenceResult,
    useMoA,
    effectiveSystemPrompt,
    copilotCausalWeightsBefore,
    copilotFedCycleId,
    shouldRunFederationDelta,
    toolLibraryIds: _toolLibraryIds,
  } = opts;

  const { workspaceId, userId, service, message, memStack } = ctx;
  // workerId scopes all ai_memory writes to a specific AI Worker.
  // Without it, memories are workspace-level and leak across all workers' "While you were away".
  const _workerId: string | undefined = (ctx as any).workerId ?? undefined;
  const _sessionId = ctx.requestId;
  const _rlExecutionMs = Date.now() - streamStartMs;

  // ── 1. RL Quality Recording ────────────────────────────────────────────────
  let _rlQuality = 0.5;
  try {
    const { computeAgentQuality, recordAgentOutcome } = await import('@/lib/brain/agent-rl');
    const _rlDomain = detectedIntent ?? 'general';
    _rlQuality = computeAgentQuality(
      streamedAssistantText ?? '',
      null,
      _rlExecutionMs,
      _rlDomain
    );

    void recordAgentOutcome(service, {
      agentId: `copilot_${workspaceId}_${Date.now()}`,
      domain: _rlDomain,
      taskDescription: message.trim().slice(0, 200),
      resultSummary: streamedAssistantText.slice(0, 500),
      quality: _rlQuality,
      executionMs: _rlExecutionMs,
      organizationId: workspaceId,
      userId,
    }).catch((rlErr: unknown) =>
      logger.warn('[PostFlight] RL outcome recording failed:', rlErr instanceof Error ? rlErr.message : String(rlErr))
    );
  } catch (rlErr: unknown) {
    logger.warn('[PostFlight] RL import failed:', rlErr instanceof Error ? rlErr.message : String(rlErr));
  }

  // ── 1.5. ADR-027 PART 7: Capability Gap Recording ─────────────────────────
  // When response quality is low, record the domain+query as a capability gap
  // so the tool synthesis pipeline can generate better tooling for future use.
  // ADR-031 Phase 4: Use SAGE-tuned threshold instead of hard-coded 0.5.
  if (detectedIntent) {
    void (async () => {
      try {
        const { getGapDetectionThreshold } = await import("@/lib/brain/tool-lifecycle");
        const gapThreshold = await getGapDetectionThreshold(service, workspaceId);
        if (_rlQuality < gapThreshold) {
          const { recordCapabilityGap } = await import("@/lib/brain/capability-synthesizer");
          await recordCapabilityGap({
            domain: detectedIntent,
            query: message,
            qualityScore: _rlQuality,
            supabase: service,
            orgId: workspaceId,
          });
        }
      } catch {
        // fire-and-forget — never propagate
      }
    })();
  }

  // ── 1.5b. ADR-030: Self-Evolving Reflex Gap Recording ──────────────────────
  // When LLM response quality is consistently low for a domain (< 0.4), record
  // a reflex gap so the tool-maker can synthesize a deterministic reflex that
  // intercepts before the LLM next time. This is the self-evolving loop:
  //   Post-flight detects failure → records gap → tool-maker synthesizes reflex
  //   → promoted reflex starts bypassing the LLM for that pattern.
  if (_rlQuality < 0.4 && detectedIntent && message.trim().length > 10) {
    void import("@/lib/brain/reflex-engine")
      .then(({ recordReflexGap }) =>
        recordReflexGap(service, workspaceId, {
          triggerMessage: message.trim(),
          failureReason: `Low RL quality (${_rlQuality.toFixed(2)}) for domain ${detectedIntent}`,
          suggestedAction: `Create deterministic reflex for "${detectedIntent}" domain pattern`,
          domain: detectedIntent,
          occurrences: 1,
        })
      )
      .catch(() => {}); // fire-and-forget
  }

  // ── 1.6. ADR-027 PART 7E: Tool Invocation RL Tracking ───────────────────
  // If synthesized tools were injected in this request (working memory has
  // capabilitiesBlock), record the response quality as a tool invocation
  // outcome so the RL loop can update tool quality scores over time.
  if (detectedIntent && _rlQuality > 0) {
    void import("@/lib/brain/tool-registry")
      .then(async ({ getToolsForDomain, recordToolInvocation }) => {
        const tools = await getToolsForDomain(service, workspaceId, detectedIntent);
        for (const tool of tools.slice(0, 3)) { // max 3 tools per domain
          await recordToolInvocation(service, workspaceId, {
            toolId: tool.id,
            domain: detectedIntent,
            success: _rlQuality >= 0.6,
            executionMs: 0, // copilot doesn't track per-tool execution time
            timestamp: new Date().toISOString(),
          });
        }
      })
      .catch(() => {}); // fire-and-forget
  }

  // ── 1.7. ADR-028: capability_library Tool Invocation Tracking ────────────
  // Record invocations for tools retrieved from capability_library via CRAFT
  // (working-memory toolLibraryIds). Also writes a per-invocation outcome row
  // to ai_memory for RL aggregation by the cognitive-cycle lifecycle runner.
  if (_toolLibraryIds?.length && _rlQuality > 0) {
    for (const toolId of _toolLibraryIds.slice(0, 5)) {
      void Promise.resolve(service.rpc("increment_tool_invocation", { p_tool_id: toolId })).catch(() => {});
    }
    // Record per-invocation outcome for RL aggregation
    void Promise.resolve(service.from("ai_memory").insert({
      organization_id: workspaceId,
      memory_type: "tool_invocation",
      domain: `tool-invocation:${detectedIntent ?? "general"}`,
      content: JSON.stringify({
        toolIds: _toolLibraryIds,
        quality: _rlQuality,
        success: _rlQuality >= 0.6,
        source: "capability_library",
        timestamp: new Date().toISOString(),
      }),
      importance: _rlQuality >= 0.6 ? 0.7 : 0.5,
      metadata: { source: "capability_library", ...(_workerId ? { worker_id: _workerId } : {}) },
    })).catch(() => {});
  }

  // ── 2. Decision Pattern Training ──────────────────────────────────────────
  // Write high-quality decisions to ai_memory as pattern training data.
  // Uses upsert on (organization_id, memory_type, domain) unique index.
  try {
    const _rlDomain = detectedIntent ?? 'general';
    if (_rlQuality >= 0.6) {
      void Promise.resolve(
        service.from('ai_memory').upsert({
          organization_id: workspaceId,
          domain: `routing.${_rlDomain}`,
          memory_type: 'pattern',
          content: `Query: "${message.trim().slice(0, 200)}" → Intent: ${_rlDomain}, Quality: ${(_rlQuality * 100).toFixed(0)}%`,
          importance: _rlQuality,
          metadata: {
            type: 'claude_decision_pattern',
            ...(_workerId ? { worker_id: _workerId } : {}),
            record: {
              sessionId: _sessionId,
              query: message.trim().slice(0, 200),
              detectedIntent: _rlDomain,
              modelSelected: v4SmartModel,
              responseQuality: _rlQuality,
              durationMs: _rlExecutionMs,
            },
          },
        }, {
          onConflict: 'organization_id,memory_type,domain',
          ignoreDuplicates: false,
        })
      ).catch(() => {}); // fire-and-forget
    }

    // Emit llm_decision signal for ALL queries (including low-quality — brain needs
    // negative training examples to learn what routing patterns to avoid).
    if (memStack) {
      const { createBrainFeedbackBus: _decisionFeedbackBus } = memStack;
      const _decisionBus = _decisionFeedbackBus({ supabase: service, organizationId: workspaceId });
      void _decisionBus.emitSignal({
        sourceDomain: 'copilot.routing',
        signalType: 'llm_decision',
        signalValue: _rlQuality,
        entityType: 'routing_decision',
        entityId: _sessionId,
        metadata: {
          intent: _rlDomain,
          model: v4SmartModel,
        },
      }).catch(() => {}); // fire-and-forget
    }

    // ADR-027: Capture routing feedback — links routing decision to response quality
    void import("@/lib/brain/orchestration-capture").then(({ captureRoutingFeedback }) => {
      captureRoutingFeedback(service, workspaceId, {
        query: message.trim().slice(0, 200),
        routedTo: _rlDomain,
        serviceType: seaasResult ? 'se-aas' : accountingResult ? 'aas' : deliveryIntelligenceResult ? 'se-aas' : 'copilot',
        responseQuality: _rlQuality,
        durationMs: _rlExecutionMs,
        aiWorkerId: _workerId, // scope routing feedback to the specific worker
      });
    }).catch(() => {}); // fire-and-forget
  } catch { /* non-fatal */ }

  // ── 2.5. Federated Knowledge Capture ──────────────────────────────────────
  // Write the raw response to federated_knowledge for cross-org learning.
  // Complements ai_memory (per-org patterns) with federated_knowledge (promoted cross-org).
  if (streamedAssistantText && streamedAssistantText.length > 100 && _rlQuality >= 0.45) {
    void import("@/lib/brain/claude-learning-capture").then(({ captureStreamedResponse }) => {
      captureStreamedResponse(streamedAssistantText, _rlExecutionMs, {
        supabase: service,
        organizationId: workspaceId,
        domain: `copilot.${detectedIntent ?? 'general'}`,
        inputSummary: message.trim().slice(0, 200),
        qualityThreshold: 0.45,
      });
    }).catch(() => {}); // fire-and-forget
  }

  // ── 3. Response Harvesting (Haiku key fact extraction → ai_memory) ─────────
  if (streamedAssistantText && streamedAssistantText.length > 200) {
    void (async () => {
      try {
        const { default: AnthropicHarvest } = await import('@anthropic-ai/sdk');
        const harvestClient = new AnthropicHarvest({ apiKey: process.env.ANTHROPIC_API_KEY });
        const harvestResp = await harvestClient.messages.create({
          model: 'claude-haiku-4-5-20251001',
          max_tokens: 512,
          messages: [{
            role: 'user',
            content: `Extract key facts and patterns from this AI response (domain: ${detectedIntent ?? 'general'}).

Response: ${streamedAssistantText.slice(0, 2000)}

Return JSON: {"keyFacts": ["..."], "patterns": ["..."], "decisions": ["..."]}`,
          }],
        });

        const harvestContent = harvestResp.content[0];
        if (harvestContent.type === 'text') {
          const jsonMatch = harvestContent.text.match(/\{[\s\S]*\}/);
          if (jsonMatch) {
            const harvest = JSON.parse(jsonMatch[0]) as { keyFacts?: string[]; patterns?: string[]; decisions?: string[] };
            const content = [
              (harvest.keyFacts ?? []).join(' | '),
              (harvest.patterns ?? []).join(' | '),
              (harvest.decisions ?? []).join(' | '),
            ].filter(Boolean).join('\n');

            if (content.length > 20) {
              await Promise.resolve(
                service.from('ai_memory').upsert({
                  organization_id: workspaceId,
                  domain: `response.${detectedIntent ?? 'general'}`,
                  memory_type: 'pattern',
                  content: content.slice(0, 1000),
                  importance: _rlQuality ?? 0.5,
                  metadata: {
                    source: 'response_harvester',
                    intent: detectedIntent,
                    model: v4SmartModel,
                    quality: _rlQuality,
                    ...(_workerId ? { worker_id: _workerId } : {}),
                  },
                }, {
                  onConflict: 'organization_id,memory_type,domain',
                  ignoreDuplicates: false,
                })
              ).catch(() => {});
            }
          }
        }
      } catch { /* non-blocking — harvest failure must never affect response */ }
    })();
  }

  // ── 4. Self-MoA Post-Stream Synthesis ─────────────────────────────────────
  if (useMoA && streamedAssistantText.length > 0) {
    void (async () => {
      try {
        const { runSelfMoA } = await import("@/lib/brain/self-moa");
        const _moaResult = await runSelfMoA(
          [{ role: "user", content: message }],
          effectiveSystemPrompt,
          v4SmartModel,
          512
        );
        if (_moaResult.usedMoA && _moaResult.synthesizedResponse) {
          await Promise.resolve(
            service.from("ai_memory").upsert({
              organization_id: workspaceId,
              memory_type: "pattern",
              domain: `moa.${detectedIntent ?? "general"}`,
              content: `Q: ${message.slice(0, 200)}\nA: ${_moaResult.synthesizedResponse.slice(0, 800)}`,
              importance: 0.85,
              metadata: {
                source: "self_moa",
                qualityBoost: _moaResult.qualityBoost,
                model: v4SmartModel,
                originalQuery: message.slice(0, 200),
                ...(_workerId ? { worker_id: _workerId } : {}),
              },
            }, {
              onConflict: "organization_id,memory_type,domain",
              ignoreDuplicates: false,
            })
          ).catch(() => {});
        }
      } catch { /* non-blocking — MoA failure must never affect response */ }
    })();
  }

  // ── 5. Chat Auto-Save ─────────────────────────────────────────────────────
  try {
    const conversationHistory = (ctx as any)._conversationHistory as Array<{ role: string; content: string }> | undefined;
    const sessionDate = new Date().toISOString().slice(0, 10);
    const sessionTitle = message.trim().slice(0, 80) || "New conversation";

    const updatedMessages: Array<{ role: string; content: string; timestamp: string }> = [
      ...(conversationHistory ?? []).map((h) => ({ role: h.role, content: h.content, timestamp: "" })),
      { role: "user", content: message.trim(), timestamp: new Date().toISOString() },
      ...(streamedAssistantText
        ? [{ role: "assistant", content: streamedAssistantText.trim(), timestamp: new Date().toISOString() }]
        : []),
    ];

    await service
      .from("conversations")
      .upsert(
        {
          // Provide the client-generated conversationId so the same row is updated
          // on every turn. Without an id, every turn creates a new orphaned row.
          ...(_conversationId ? { id: _conversationId } : {}),
          org_id: workspaceId,
          user_id: userId,
          title: sessionTitle,
          service_mode: seaasResult || deliveryIntelligenceResult ? "seaas" : accountingResult ? "aas" : "general",
          messages: updatedMessages,
          metadata: {
            lastDomain: detectedIntent || "general",
            sessionDate,
            workerId: (ctx as any).workerId ?? null,
          },
          updated_at: new Date().toISOString(),
        },
        {
          onConflict: "id",
          ignoreDuplicates: false, // UPDATE on conflict so multi-turn history accumulates
        }
      )
      .select("id")
      .maybeSingle();
  } catch (saveErr) {
    logger.warn("[PostFlight] Chat auto-save failed (non-fatal):", saveErr instanceof Error ? saveErr.message : String(saveErr));
  }

  // ── 6. Tier-1 Raw Knowledge Store Ingest ──────────────────────────────────
  if (workspaceId && message) {
    void (async () => {
      try {
        const { ingestConversationTurn } = await import("@/lib/brain/tier1-store");
        await Promise.allSettled([
          ingestConversationTurn(workspaceId, {
            sessionId: _sessionId,
            role: 'user',
            content: message.slice(0, 4000),
            metadata: { source: 'copilot' },
          }),
          ...(typeof streamedAssistantText === 'string' && streamedAssistantText.length > 0 ? [
            ingestConversationTurn(workspaceId, {
              sessionId: _sessionId,
              role: 'assistant',
              content: streamedAssistantText.slice(0, 4000),
              metadata: { source: 'copilot' },
            }),
          ] : []),
        ]);
      } catch (e) {
        logger.warn("[PostFlight] Conversation tier1 ingest failed", { error: String(e) });
      }
    })();
  }

  // ── 7. Mem0 Structured Fact Extraction ────────────────────────────────────
  void (async () => {
    try {
      const { extractAndUpdateMemory } = await import("@/lib/brain/mem0-extractor");
      await extractAndUpdateMemory(
        service,
        workspaceId,
        `User: ${message}\nAssistant: ${streamedAssistantText}`,
        detectedIntent ?? 'copilot'
      );
    } catch { /* non-blocking */ }
  })();

  // ── 8. Causal Federation Delta Promotion ──────────────────────────────────
  // Mirror of domain-executor Step 7: promote learned causal weight deltas to CORE.
  // shouldRunFederationDelta is pre-computed by the caller (TTL guard + snapshot size).
  if (shouldRunFederationDelta && copilotCausalWeightsBefore.size > 0) {
    void (async () => {
      try {
        const { computeAndPromoteCausalDeltas } = await import("@nexus-ai/memory-stack");
        const _fedResult = await computeAndPromoteCausalDeltas(
          service,
          workspaceId,
          copilotCausalWeightsBefore,
          copilotFedCycleId,
          {
            fedAvgLearningRate: 0.3,
            maxDelta: 0.15,
            minDelta: 0.01,
            minSampleSize: 10,
            maxPairsPerRun: 20,
          },
        );
        logger.debug(
          `[PostFlight federation] org=${workspaceId.slice(0, 8)} ` +
          `applied=${_fedResult.deltasApplied} filtered=${_fedResult.deltasFiltered} ` +
          `newPairs=${_fedResult.newPairsAdded} updatedPairs=${_fedResult.existingPairsUpdated} ` +
          `took=${_fedResult.durationMs}ms`
        );
      } catch (e: unknown) {
        logger.warn("[PostFlight] Causal delta promotion failed (non-fatal):", e instanceof Error ? e.message : String(e));
      }
    })();
  }
}
